UPDATE trinity_string SET content_loc4='您应该选择角色或生物.' WHERE entry=1;
UPDATE trinity_string SET content_loc4='您应该选择一个生物.' WHERE entry=2;
UPDATE trinity_string SET content_loc4='|cffff0000[系统消息]: %s|r' WHERE entry=3;
UPDATE trinity_string SET content_loc4='|cffff0000[游戏广播]: %s|r' WHERE entry=4;
UPDATE trinity_string SET content_loc4='这里没有此命令的帮助信息' WHERE entry=5;
UPDATE trinity_string SET content_loc4='这个命令不存在' WHERE entry=6;
UPDATE trinity_string SET content_loc4='这里没有此类子命令' WHERE entry=7;
UPDATE trinity_string SET content_loc4='命令 %s 子命令是:%s' WHERE entry=8;
UPDATE trinity_string SET content_loc4='你可以使用的命令有:' WHERE entry=9;
UPDATE trinity_string SET content_loc4='命令语法格式错误.' WHERE entry=10;
UPDATE trinity_string SET content_loc4='你的账号级别是: %i' WHERE entry=11;
UPDATE trinity_string SET content_loc4='在线人数: %u (最多时: %u) 排队人数: %u (最多时: %u)' WHERE entry=12;
UPDATE trinity_string SET content_loc4='服务器正常运行时间: %s' WHERE entry=13;
UPDATE trinity_string SET content_loc4='系统提示：玩家数据保存成功.' WHERE entry=14;
UPDATE trinity_string SET content_loc4='系统提示：保存所有玩家数据成功.' WHERE entry=15;
UPDATE trinity_string SET content_loc4='系统提示：在此服务器上有以下在线的G M:' WHERE entry=16;
UPDATE trinity_string SET content_loc4='系统提示：当前没有G M登录在这台服务器上.' WHERE entry=17;
UPDATE trinity_string SET content_loc4='系统提示：当处于飞行中时，无法这样做.' WHERE entry=18;
UPDATE trinity_string SET content_loc4='系统提示：目标在飞行中，你无法这样做.' WHERE entry=20;
UPDATE trinity_string SET content_loc4='系统提示：在战场里无法这样做.' WHERE entry=19;
UPDATE trinity_string SET content_loc4='%s 正在飞行中, 命令无效.' WHERE entry=21;
UPDATE trinity_string SET content_loc4='系统提示：你没有在骑乘状态, 因此你不能卸下骑乘.' WHERE entry=22;
UPDATE trinity_string SET content_loc4='系统提示：在战斗中无法这样做.' WHERE entry=23;
UPDATE trinity_string SET content_loc4='系统提示：您最近已经使用过它.' WHERE entry=24;
UPDATE trinity_string SET content_loc4='系统提示：您的密码不能设置超过16个字符长度(客户极限), 密码没被改变' WHERE entry=25;
UPDATE trinity_string SET content_loc4='系统提示：密码已经修改.' WHERE entry=26;
UPDATE trinity_string SET content_loc4='系统提示：新新口令不匹配或旧密码是错误的.' WHERE entry=27;
UPDATE trinity_string SET content_loc4='系统提示：你的账号现在被锁定.' WHERE entry=28;
UPDATE trinity_string SET content_loc4='系统提示：你的账号已取消锁定.' WHERE entry=29;
UPDATE trinity_string SET content_loc4='排名 ' WHERE entry=30;
UPDATE trinity_string SET content_loc4=' [学会]' WHERE entry=31;
UPDATE trinity_string SET content_loc4=' [学习]' WHERE entry=32;
UPDATE trinity_string SET content_loc4=' [被动的]' WHERE entry=33;
UPDATE trinity_string SET content_loc4=' [天赋]' WHERE entry=34;
UPDATE trinity_string SET content_loc4=' [激活]' WHERE entry=35;
UPDATE trinity_string SET content_loc4=' [完成]' WHERE entry=36;
UPDATE trinity_string SET content_loc4=' (离线)' WHERE entry=37;
UPDATE trinity_string SET content_loc4='开' WHERE entry=38;
UPDATE trinity_string SET content_loc4='关' WHERE entry=39;
UPDATE trinity_string SET content_loc4='你是: %s' WHERE entry=40;
UPDATE trinity_string SET content_loc4='显示' WHERE entry=41;
UPDATE trinity_string SET content_loc4='隐藏' WHERE entry=42;
UPDATE trinity_string SET content_loc4='完成' WHERE entry=43;
UPDATE trinity_string SET content_loc4='你' WHERE entry=44;
UPDATE trinity_string SET content_loc4=' <未知> ' WHERE entry=45;
UPDATE trinity_string SET content_loc4='<错误>' WHERE entry=46;
UPDATE trinity_string SET content_loc4='<查无此人>' WHERE entry=47;
UPDATE trinity_string SET content_loc4='未知' WHERE entry=48;
UPDATE trinity_string SET content_loc4='你必须达到 %u 级后进入.' WHERE entry=49;
UPDATE trinity_string SET content_loc4='你必须达到 %u 级,并且拥有道具 %s 方可进入.' WHERE entry=50;
UPDATE trinity_string SET content_loc4='你好! 准备学习什么技能吗?' WHERE entry=51;
UPDATE trinity_string SET content_loc4='Invaid item count (%u) for item %u' WHERE entry=52;
UPDATE trinity_string SET content_loc4='Mail can''t have more %u item stacks' WHERE entry=53;
UPDATE trinity_string SET content_loc4='The new passwords do not match' WHERE entry=54;
UPDATE trinity_string SET content_loc4='Your password can''t be longer than 16 characters (client limit), password not changed!' WHERE entry=55;
UPDATE trinity_string SET content_loc4='Current Message of the day: 
%s' WHERE entry=56;
UPDATE trinity_string SET content_loc4='Using World DB: %s' WHERE entry=57;
UPDATE trinity_string SET content_loc4='Using script library: %s' WHERE entry=58;
UPDATE trinity_string SET content_loc4='Using creature EventAI: %s' WHERE entry=59;
UPDATE trinity_string SET content_loc4='Online players: %u (max: %u)' WHERE entry=60;
UPDATE trinity_string SET content_loc4='Up to %u expansion allowed now.' WHERE entry=61;
UPDATE trinity_string SET content_loc4='全区广播:\n' WHERE entry=100;
UPDATE trinity_string SET content_loc4='地图: %u (%s) 地域: %u (%s) 地区: %u (%s) Phase: %u
X: %f Y: %f Z: %f Orientation: %f
grid[%u,%u]cell[%u,%u] InstanceID: %u
 ZoneX: %f ZoneY: %f
GroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE entry=101;
UPDATE trinity_string SET content_loc4='%s 已被远距传送.' WHERE entry=102;
UPDATE trinity_string SET content_loc4='你可以召唤一个玩家到你的副本，前提是必须在同一队伍，而且你是队长.' WHERE entry=103;
UPDATE trinity_string SET content_loc4='你无法传送到玩家 %s 的副本，因为你们不在同一队伍.' WHERE entry=104;
UPDATE trinity_string SET content_loc4='传送到不是同一队伍的玩家 %s 的副本需要开启ＧＭ模式.' WHERE entry=105;
UPDATE trinity_string SET content_loc4='你无法传送到玩家  %s 从副本到副本.' WHERE entry=106;
UPDATE trinity_string SET content_loc4='你不能召唤这个玩家 %s 从副本到副本.' WHERE entry=107;
UPDATE trinity_string SET content_loc4='你正在召唤 %s%s.' WHERE entry=108;
UPDATE trinity_string SET content_loc4='系统提示：你正在被 %s 召唤中.' WHERE entry=109;
UPDATE trinity_string SET content_loc4='你正在传送  %s%s to %s.' WHERE entry=110;
UPDATE trinity_string SET content_loc4='系统提示：你正在被 %s 传送.' WHERE entry=111;
UPDATE trinity_string SET content_loc4='玩家 (%s) 不存在.' WHERE entry=112;
UPDATE trinity_string SET content_loc4='出现在 %s 的地点.' WHERE entry=113;
UPDATE trinity_string SET content_loc4='%s 出现在你的位置.' WHERE entry=114;
UPDATE trinity_string SET content_loc4='无效参数.' WHERE entry=115;
UPDATE trinity_string SET content_loc4='没有选定角色.' WHERE entry=116;
UPDATE trinity_string SET content_loc4='%s 不在同一小组里.' WHERE entry=117;
UPDATE trinity_string SET content_loc4='你改变了 %s 的血量值 HP to %i/%i.' WHERE entry=118;
UPDATE trinity_string SET content_loc4='%s 改变了你的血量值 HP 到 %i/%i.' WHERE entry=119;
UPDATE trinity_string SET content_loc4='你改变了 %s 的魔法值 MANA 到 %i/%i.' WHERE entry=120;
UPDATE trinity_string SET content_loc4='%s 改变了你的魔法值 MANA 到 %i/%i.' WHERE entry=121;
UPDATE trinity_string SET content_loc4='你改变了 %s 的能量值 ENERGY 到 %i/%i.' WHERE entry=122;
UPDATE trinity_string SET content_loc4='%s 改变了你的能量值 ENERGY 到 %i/%i.' WHERE entry=123;
UPDATE trinity_string SET content_loc4='当前的能量: %u' WHERE entry=124;
UPDATE trinity_string SET content_loc4='你改变了 %s 的怒气值 RAGE 到 %i/%i.' WHERE entry=125;
UPDATE trinity_string SET content_loc4='%s 改变了你的怒气值 RAGE 到 %i/%i.' WHERE entry=126;
UPDATE trinity_string SET content_loc4='你改变了 %s 的等级 LVL 到 %i.' WHERE entry=127;
UPDATE trinity_string SET content_loc4='GUID %i, faction is %i, flags is %i, npcflag is %i' WHERE entry=128;
UPDATE trinity_string SET content_loc4='错误 faction: %u (not found in factiontemplate.dbc).' WHERE entry=129;
UPDATE trinity_string SET content_loc4='你改变了 GUID=%i ''s Faction to %i, flags to %i,' WHERE entry=130;
UPDATE trinity_string SET content_loc4='你改变了 the spellflatid=%i, val= %i, mark =%i ' WHERE entry=131;
UPDATE trinity_string SET content_loc4='%s 改变了你的 spellflatid=%i, val= %i, mark =%i.' WHERE entry=132;
UPDATE trinity_string SET content_loc4='%s 获得了所有的计程节点 (直到注销).' WHERE entry=133;
UPDATE trinity_string SET content_loc4='%s 没有更多地可获得的计程节点(仅显示容易接近的).' WHERE entry=134;
UPDATE trinity_string SET content_loc4='%s 给你进入所有计程车节点 (直到注销).' WHERE entry=135;
UPDATE trinity_string SET content_loc4='%s 已取消进出所有计程车节点(仅显示仍然容易接近的).' WHERE entry=136;
UPDATE trinity_string SET content_loc4='你设置了所有的速度到 %2.2f 从基础值 %s.' WHERE entry=137;
UPDATE trinity_string SET content_loc4='%s 设置了你所有的速度到 %2.2f 从基础值.' WHERE entry=138;
UPDATE trinity_string SET content_loc4='你设置了移动速度到 %2.2f 从基础值 %s.' WHERE entry=139;
UPDATE trinity_string SET content_loc4='%s 设置了你的移动速度到 %2.2f 从基础值.' WHERE entry=140;
UPDATE trinity_string SET content_loc4='你设置了游泳速度到 %2.2f 从基础值 %s.' WHERE entry=141;
UPDATE trinity_string SET content_loc4='%s 设置了你的游泳速度到 %2.2f 从基础值.' WHERE entry=142;
UPDATE trinity_string SET content_loc4='设置了后退速度到 %2.2f 从基础值 %s.' WHERE entry=143;
UPDATE trinity_string SET content_loc4='%s 设置了你的后退速度到 %2.2f 从基础值.' WHERE entry=144;
UPDATE trinity_string SET content_loc4='你设置了飞行速度到 %2.2f 从基础值 %s.' WHERE entry=145;
UPDATE trinity_string SET content_loc4='%s 设置你的飞行速度到 %2.2f 从基础值.' WHERE entry=146;
UPDATE trinity_string SET content_loc4='你设置了这个比例 %2.2f of %s.' WHERE entry=147;
UPDATE trinity_string SET content_loc4='%s 设置你的比例为 %2.2f.' WHERE entry=148;
UPDATE trinity_string SET content_loc4='没有此类骑术.' WHERE entry=149;
UPDATE trinity_string SET content_loc4='你把一个骑术送给 %s.' WHERE entry=150;
UPDATE trinity_string SET content_loc4='%s 送给你一个骑术.' WHERE entry=151;
UPDATE trinity_string SET content_loc4='USER1: %i, ADD: %i, DIF: %i
' WHERE entry=152;
UPDATE trinity_string SET content_loc4='你拿走了所有的铜币从 %s.' WHERE entry=153;
UPDATE trinity_string SET content_loc4='%s 拿走了你所有的铜币.' WHERE entry=154;
UPDATE trinity_string SET content_loc4='你拿走了 %i 铜币从 %s.' WHERE entry=155;
UPDATE trinity_string SET content_loc4='%s 拿走了 %i 铜币从你这里.' WHERE entry=156;
UPDATE trinity_string SET content_loc4='你把 %i 铜币给了 %s.' WHERE entry=157;
UPDATE trinity_string SET content_loc4='%s 给你 %i  铜币.' WHERE entry=158;
UPDATE trinity_string SET content_loc4='你听到声音 %u.' WHERE entry=159;
UPDATE trinity_string SET content_loc4='USER2: %i, ADD: %i, RESULT: %i
' WHERE entry=160;
UPDATE trinity_string SET content_loc4='Removed bit %i in field %i.' WHERE entry=161;
UPDATE trinity_string SET content_loc4='Set bit %i in field %i.' WHERE entry=162;
UPDATE trinity_string SET content_loc4='远距传送地点表是空的!' WHERE entry=163;
UPDATE trinity_string SET content_loc4='远距传送地点没被发现!' WHERE entry=164;
UPDATE trinity_string SET content_loc4='需要搜索参数.' WHERE entry=165;
UPDATE trinity_string SET content_loc4='没有远距传物地点匹配您的请求.' WHERE entry=166;
UPDATE trinity_string SET content_loc4='发现地点是: ' WHERE entry=168;
UPDATE trinity_string SET content_loc4='邮件寄给 %s' WHERE entry=169;
UPDATE trinity_string SET content_loc4='你试着听声音 %u 但是它并不存在.' WHERE entry=170;
UPDATE trinity_string SET content_loc4='You can''t teleport self to self!' WHERE entry=171;
UPDATE trinity_string SET content_loc4='%s changed your runes to %i/%i/%i/%i/%i/%i.' WHERE entry=172;
UPDATE trinity_string SET content_loc4='Current runes: %u/%u/%u/%u/%u/%u' WHERE entry=173;
UPDATE trinity_string SET content_loc4='You changed runic power of %s to %i/%i.' WHERE entry=174;
UPDATE trinity_string SET content_loc4='Liquid level: %f, ground: %f, type: %d, status: %d' WHERE entry=175;
UPDATE trinity_string SET content_loc4='没有选择.' WHERE entry=200;
UPDATE trinity_string SET content_loc4='Object GUID is: lowpart %u highpart %X' WHERE entry=201;
UPDATE trinity_string SET content_loc4='这个名字长度超过了 %i 字符.' WHERE entry=202;
UPDATE trinity_string SET content_loc4='错误,名字只能包含字符 A-Z 和 a-z.' WHERE entry=203;
UPDATE trinity_string SET content_loc4='次级名字太长超过了 %i 字符.' WHERE entry=204;
UPDATE trinity_string SET content_loc4='未能实施.' WHERE entry=205;
UPDATE trinity_string SET content_loc4='物品 ''%i'' ''%s'' 以加入到列表且最大数 ''%i'' 复生时间 ''%i''' WHERE entry=206;
UPDATE trinity_string SET content_loc4='物品 ''%i'' 在数据库里没有找到.' WHERE entry=207;
UPDATE trinity_string SET content_loc4='物品 ''%i'' ''%s'' 已经从商人列表中删除.' WHERE entry=208;
UPDATE trinity_string SET content_loc4='物品 ''%i'' 没有找到在商人的列表里.' WHERE entry=209;
UPDATE trinity_string SET content_loc4='法术 %s 重置.' WHERE entry=211;
UPDATE trinity_string SET content_loc4='法术 %s 将在下次登陆时重置.' WHERE entry=212;
UPDATE trinity_string SET content_loc4='天赋 %s 重置.' WHERE entry=213;
UPDATE trinity_string SET content_loc4='天赋 %s 将在下次登陆时重置.' WHERE entry=214;
UPDATE trinity_string SET content_loc4='你的法术已经重置了.' WHERE entry=215;
UPDATE trinity_string SET content_loc4='你的天赋已经重置了.' WHERE entry=216;
UPDATE trinity_string SET content_loc4='未知的参数 ''%s'' 为 .resetall 命令. 键入完整的正确参数名字.' WHERE entry=217;
UPDATE trinity_string SET content_loc4='法术将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=218;
UPDATE trinity_string SET content_loc4='天赋将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=219;
UPDATE trinity_string SET content_loc4='生物 (GUID: %u) 没有飞行点发现.' WHERE entry=220;
UPDATE trinity_string SET content_loc4='生物 (GUID: %u) 飞行终点没有找到.' WHERE entry=221;
UPDATE trinity_string SET content_loc4='生物 (GUID: %u) 没有飞行点发现 - 请用  ''wpguid''. 现在设法发现它由它的位置...' WHERE entry=222;
UPDATE trinity_string SET content_loc4='生物 (GUID: %u) 没有飞行点发现 - 这是一个MaNGOS db 问题 (single float).' WHERE entry=223;
UPDATE trinity_string SET content_loc4='选择的生物被忽略 - 提供的 GUID 已经被占用.' WHERE entry=224;
UPDATE trinity_string SET content_loc4='生物 (GUID: %u) 没有找到.' WHERE entry=225;
UPDATE trinity_string SET content_loc4='您必须选择一个视觉飞行点.' WHERE entry=226;
UPDATE trinity_string SET content_loc4='没有找到视觉飞行点.' WHERE entry=227;
UPDATE trinity_string SET content_loc4='不能创建视觉飞行点的 生物ID: %d' WHERE entry=228;
UPDATE trinity_string SET content_loc4='所有视觉飞行点消除.' WHERE entry=229;
UPDATE trinity_string SET content_loc4='不能创建 飞行点-生物的 ID: %d' WHERE entry=230;
UPDATE trinity_string SET content_loc4='没有 GUID 被提供.' WHERE entry=231;
UPDATE trinity_string SET content_loc4='没有提供飞行点数值.' WHERE entry=232;
UPDATE trinity_string SET content_loc4='根据要求为 ''%s''.' WHERE entry=233;
UPDATE trinity_string SET content_loc4='飞行点 %i 添加到 GUID: %d' WHERE entry=234;
UPDATE trinity_string SET content_loc4='飞行点 %d 已添加.' WHERE entry=235;
UPDATE trinity_string SET content_loc4='飞行点已变动.' WHERE entry=236;
UPDATE trinity_string SET content_loc4='飞行点 %s 已修改.' WHERE entry=237;
UPDATE trinity_string SET content_loc4='飞行点出口成功.' WHERE entry=238;
UPDATE trinity_string SET content_loc4='没有飞行点被发现在数据库里.' WHERE entry=239;
UPDATE trinity_string SET content_loc4='文件已导入.' WHERE entry=240;
UPDATE trinity_string SET content_loc4='飞行点取消.' WHERE entry=241;
UPDATE trinity_string SET content_loc4='警告: 不能删除这个飞行点从世界里且 ID: %d' WHERE entry=242;
UPDATE trinity_string SET content_loc4='出现这种情况，是因为飞行点过于远离你.' WHERE entry=243;
UPDATE trinity_string SET content_loc4='这个飞行点已经从数据库删除, 但不是从世界这里.' WHERE entry=244;
UPDATE trinity_string SET content_loc4='他们将消失，当服务器重新启动之后.' WHERE entry=245;
UPDATE trinity_string SET content_loc4='飞行点 %d: 生物信息: %s, GUID: %d' WHERE entry=246;
UPDATE trinity_string SET content_loc4='等待时间: %d' WHERE entry=247;
UPDATE trinity_string SET content_loc4='模型 %d: %d' WHERE entry=248;
UPDATE trinity_string SET content_loc4='表情: %d' WHERE entry=249;
UPDATE trinity_string SET content_loc4='技能: %d' WHERE entry=250;
UPDATE trinity_string SET content_loc4='文本%d (ID: %i): %s' WHERE entry=251;
UPDATE trinity_string SET content_loc4='AI脚本: %s' WHERE entry=252;
UPDATE trinity_string SET content_loc4='强制修改玩家名 %s, 将于下次登录时生效.' WHERE entry=253;
UPDATE trinity_string SET content_loc4='强制修改玩家名 %s (GUID #%u), 将于下次登录时生效.' WHERE entry=254;
UPDATE trinity_string SET content_loc4='飞行点-生物 (GUID: %u) 没有找到.' WHERE entry=255;
UPDATE trinity_string SET content_loc4='不能查找NPC...' WHERE entry=256;
UPDATE trinity_string SET content_loc4='生物运动方式设置为 ''%s'', 飞行点去除 (如果任何).' WHERE entry=257;
UPDATE trinity_string SET content_loc4='生物运动方式设置为 ''%s'', 飞行点没有去除.' WHERE entry=258;
UPDATE trinity_string SET content_loc4='错误值, 请用 on 或 off ' WHERE entry=259;
UPDATE trinity_string SET content_loc4='设置已保存.' WHERE entry=260;
UPDATE trinity_string SET content_loc4='设置已保存, 你可能需要重新清理你的客户缓存.' WHERE entry=261;
UPDATE trinity_string SET content_loc4='区域触发(传送门) ID %u 没有发现! ' WHERE entry=262;
UPDATE trinity_string SET content_loc4='目标地图或坐标无效 (X: %f Y: %f MapId: %u)' WHERE entry=263;
UPDATE trinity_string SET content_loc4='区域传送门无效 (X: %f Y: %f AreaId: %u)' WHERE entry=264;
UPDATE trinity_string SET content_loc4='Zone %u (%s) is part of instanceable map %u (%s)' WHERE entry=265;
UPDATE trinity_string SET content_loc4='没任何发现!' WHERE entry=266;
UPDATE trinity_string SET content_loc4='对象没有找到!' WHERE entry=267;
UPDATE trinity_string SET content_loc4='生物没有找到!' WHERE entry=268;
UPDATE trinity_string SET content_loc4='警告: 怪物发现超过一次 - 你将使用的是第一个在DB数据里的记录.' WHERE entry=269;
UPDATE trinity_string SET content_loc4='生物已经移除.' WHERE entry=270;
UPDATE trinity_string SET content_loc4='生物已经移动. ' WHERE entry=271;
UPDATE trinity_string SET content_loc4='生物 (GUID:%u) 必须与玩家在同样的地图!' WHERE entry=272;
UPDATE trinity_string SET content_loc4='游戏对象 (GUID: %u) 没有找到.' WHERE entry=273;
UPDATE trinity_string SET content_loc4='游戏对象 (GUID: %u) 有一个参考于没有找到生物 %u 是名单, 不能被删除.' WHERE entry=274;
UPDATE trinity_string SET content_loc4='游戏对象 (GUID: %u) 去除.' WHERE entry=275;
UPDATE trinity_string SET content_loc4='游戏对象 (GUID: %u) 转动.' WHERE entry=276;
UPDATE trinity_string SET content_loc4='游戏对象 (GUID: %u) 移动.' WHERE entry=277;
UPDATE trinity_string SET content_loc4='你必须选择一个商人' WHERE entry=278;
UPDATE trinity_string SET content_loc4='你必须使用物品的id' WHERE entry=279;
UPDATE trinity_string SET content_loc4='商人设置了太多的物品 (最多128)' WHERE entry=280;
UPDATE trinity_string SET content_loc4='你不能踢出你自己，使用退出代替.' WHERE entry=281;
UPDATE trinity_string SET content_loc4='角色 %s 已踢出.' WHERE entry=282;
UPDATE trinity_string SET content_loc4='接受悄悄话: %s' WHERE entry=284;
UPDATE trinity_string SET content_loc4='接受悄悄话: ON' WHERE entry=285;
UPDATE trinity_string SET content_loc4='接受悄悄话: OFF' WHERE entry=286;
UPDATE trinity_string SET content_loc4='生物 (GUID: %u) 没有找到.' WHERE entry=287;
UPDATE trinity_string SET content_loc4='票数量: %i 出示新的票: %s ' WHERE entry=288;
UPDATE trinity_string SET content_loc4='新票开始于 %s' WHERE entry=289;
UPDATE trinity_string SET content_loc4='Ticket of %s (Last updated: %s):
%s' WHERE entry=290;
UPDATE trinity_string SET content_loc4='新票显示: ON' WHERE entry=291;
UPDATE trinity_string SET content_loc4='新票显示: OFF' WHERE entry=292;
UPDATE trinity_string SET content_loc4='票 %i 不存在.' WHERE entry=293;
UPDATE trinity_string SET content_loc4='所有票已删除.' WHERE entry=294;
UPDATE trinity_string SET content_loc4='角色 %s 票已删除.' WHERE entry=295;
UPDATE trinity_string SET content_loc4='票已删除.' WHERE entry=296;
UPDATE trinity_string SET content_loc4='复生间隔改变为: %i' WHERE entry=297;
UPDATE trinity_string SET content_loc4='复生时间改变为: %i' WHERE entry=298;
UPDATE trinity_string SET content_loc4=' %s 的荣誉被设置到 %u!' WHERE entry=299;
UPDATE trinity_string SET content_loc4='你的闲谈将被关闭 %u 分钟.' WHERE entry=300;
UPDATE trinity_string SET content_loc4='你被关闭了 %s 的聊天时间 %u 分钟.' WHERE entry=301;
UPDATE trinity_string SET content_loc4='玩的聊天已经可以使用.' WHERE entry=302;
UPDATE trinity_string SET content_loc4='你的聊天已经可以使用.' WHERE entry=303;
UPDATE trinity_string SET content_loc4='你已经可以使用 %s 的聊天了.' WHERE entry=304;
UPDATE trinity_string SET content_loc4='Faction %s (%u) reputation of %s was set to %5d!' WHERE entry=305;
UPDATE trinity_string SET content_loc4='The arena points of %s was set to %u!' WHERE entry=306;
UPDATE trinity_string SET content_loc4='没有阵营被发现' WHERE entry=307;
UPDATE trinity_string SET content_loc4='阵营 %i 未知!' WHERE entry=308;
UPDATE trinity_string SET content_loc4='无效的参数 %s' WHERE entry=309;
UPDATE trinity_string SET content_loc4='delta must be between 0 and %d (inclusive)' WHERE entry=310;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE entry=311;
UPDATE trinity_string SET content_loc4=' [显示状态]' WHERE entry=312;
UPDATE trinity_string SET content_loc4=' [交战状态]' WHERE entry=313;
UPDATE trinity_string SET content_loc4=' [和平状态]' WHERE entry=314;
UPDATE trinity_string SET content_loc4=' [潜行状态]' WHERE entry=315;
UPDATE trinity_string SET content_loc4=' [invisible forced]' WHERE entry=316;
UPDATE trinity_string SET content_loc4=' [inactive]' WHERE entry=317;
UPDATE trinity_string SET content_loc4='仇恨' WHERE entry=318;
UPDATE trinity_string SET content_loc4='敌对' WHERE entry=319;
UPDATE trinity_string SET content_loc4='不友好' WHERE entry=320;
UPDATE trinity_string SET content_loc4='中立' WHERE entry=321;
UPDATE trinity_string SET content_loc4='友好的' WHERE entry=322;
UPDATE trinity_string SET content_loc4='荣誉的' WHERE entry=323;
UPDATE trinity_string SET content_loc4='尊敬的' WHERE entry=324;
UPDATE trinity_string SET content_loc4='高贵的' WHERE entry=325;
UPDATE trinity_string SET content_loc4='Faction %s (%u) can''not have reputation.' WHERE entry=326;
UPDATE trinity_string SET content_loc4=' [no reputation]' WHERE entry=327;
UPDATE trinity_string SET content_loc4='Characters at account %s (Id: %u)' WHERE entry=328;
UPDATE trinity_string SET content_loc4='  %s (GUID %u)' WHERE entry=329;
UPDATE trinity_string SET content_loc4='真没找到玩家!' WHERE entry=330;
UPDATE trinity_string SET content_loc4='Extended item cost %u not exist' WHERE entry=331;
UPDATE trinity_string SET content_loc4='GM 模式开启' WHERE entry=332;
UPDATE trinity_string SET content_loc4='GM 模式关闭' WHERE entry=333;
UPDATE trinity_string SET content_loc4='GM Chat Badge is ON' WHERE entry=334;
UPDATE trinity_string SET content_loc4='GM Chat Badge is OFF' WHERE entry=335;
UPDATE trinity_string SET content_loc4='You repair all %s''s items.' WHERE entry=336;
UPDATE trinity_string SET content_loc4='All your items repaired by %s.' WHERE entry=337;
UPDATE trinity_string SET content_loc4='You set waterwalk mode %s for %s.' WHERE entry=338;
UPDATE trinity_string SET content_loc4='Your waterwalk mode %s by %s.' WHERE entry=339;
UPDATE trinity_string SET content_loc4='%s is now following you.' WHERE entry=340;
UPDATE trinity_string SET content_loc4='%s is not following you.' WHERE entry=341;
UPDATE trinity_string SET content_loc4='%s is now not following you.' WHERE entry=342;
UPDATE trinity_string SET content_loc4='Creature (Entry: %u) cannot be tamed.' WHERE entry=343;
UPDATE trinity_string SET content_loc4='You already have pet.' WHERE entry=344;
UPDATE trinity_string SET content_loc4='Forced customize for player %s will be requested at next login.' WHERE entry=345;
UPDATE trinity_string SET content_loc4='Forced customize for player %s (GUID #%u) will be requested at next login.' WHERE entry=346;
UPDATE trinity_string SET content_loc4='TaxiNode ID %u not found!' WHERE entry=347;
UPDATE trinity_string SET content_loc4='Game Object (Entry: %u) have invalid data and can''t be spawned' WHERE entry=348;
UPDATE trinity_string SET content_loc4='|cffff0000[系统信息]:|rScripts reloaded' WHERE entry=400;
UPDATE trinity_string SET content_loc4='你改变了 %s 的安全等级为 %i.' WHERE entry=401;
UPDATE trinity_string SET content_loc4='%s 改变了你的安全等级为 %i.' WHERE entry=402;
UPDATE trinity_string SET content_loc4='你这是低的防护等级.' WHERE entry=403;
UPDATE trinity_string SET content_loc4='生物移动点取消.' WHERE entry=404;
UPDATE trinity_string SET content_loc4='生物移动点生效.' WHERE entry=405;
UPDATE trinity_string SET content_loc4='这个区域的天气不能被更改.' WHERE entry=406;
UPDATE trinity_string SET content_loc4='本服务器天气系统取消.' WHERE entry=407;
UPDATE trinity_string SET content_loc4='%s 被禁止的为 %s. 操作: %s.' WHERE entry=408;
UPDATE trinity_string SET content_loc4='%s 被永久禁止的为 %s.' WHERE entry=409;
UPDATE trinity_string SET content_loc4='%s %s 没有发现.' WHERE entry=410;
UPDATE trinity_string SET content_loc4='%s 已解除禁止.' WHERE entry=411;
UPDATE trinity_string SET content_loc4='出现错误取消禁令 %s.' WHERE entry=412;
UPDATE trinity_string SET content_loc4='没有这个帐户.' WHERE entry=413;
UPDATE trinity_string SET content_loc4='没有这个角色.' WHERE entry=414;
UPDATE trinity_string SET content_loc4='没有这样的IP 在禁止名单.' WHERE entry=415;
UPDATE trinity_string SET content_loc4='账号 %s 从来没被禁止.' WHERE entry=416;
UPDATE trinity_string SET content_loc4='历史禁止帐户 %s:' WHERE entry=417;
UPDATE trinity_string SET content_loc4='禁止日期: %s 禁止时间: %s 激活间隔: %s  原因: %s 操作者: %s' WHERE entry=418;
UPDATE trinity_string SET content_loc4='Inf.' WHERE entry=419;
UPDATE trinity_string SET content_loc4='从未' WHERE entry=420;
UPDATE trinity_string SET content_loc4='是' WHERE entry=421;
UPDATE trinity_string SET content_loc4='不' WHERE entry=422;
UPDATE trinity_string SET content_loc4='IP地址: %s 禁止日期: %s 解除禁止日期: %s 剩余: %s R' WHERE entry=423;
UPDATE trinity_string SET content_loc4='没有匹配的IP禁止地址.' WHERE entry=424;
UPDATE trinity_string SET content_loc4='没有匹配的帐户.' WHERE entry=425;
UPDATE trinity_string SET content_loc4='没有禁用的账号相匹配.' WHERE entry=426;
UPDATE trinity_string SET content_loc4='下面的IP地址符合您的格局:' WHERE entry=427;
UPDATE trinity_string SET content_loc4='以下帐户匹配您的查询:' WHERE entry=428;
UPDATE trinity_string SET content_loc4='你学会了许多法术或技能.' WHERE entry=429;
UPDATE trinity_string SET content_loc4='你已经学会了所有的会职业法术.' WHERE entry=430;
UPDATE trinity_string SET content_loc4='你已经学会了所有的本职业天赋.' WHERE entry=431;
UPDATE trinity_string SET content_loc4='你已经学会了所有的语言.' WHERE entry=432;
UPDATE trinity_string SET content_loc4='你学会了所有手工艺技能和食谱.' WHERE entry=433;
UPDATE trinity_string SET content_loc4='不能查找 ''%s''' WHERE entry=434;
UPDATE trinity_string SET content_loc4='无效的物品 id: %u' WHERE entry=435;
UPDATE trinity_string SET content_loc4='没有找到物品!' WHERE entry=436;
UPDATE trinity_string SET content_loc4='无效的游戏物品对象 id: %u' WHERE entry=437;
UPDATE trinity_string SET content_loc4='找到物品 %u: %u ( 库存 %u 邮件 %u 拍卖 %u )' WHERE entry=438;
UPDATE trinity_string SET content_loc4='找到物品对象 %u: %u' WHERE entry=439;
UPDATE trinity_string SET content_loc4='无效的生物 id: %u' WHERE entry=440;
UPDATE trinity_string SET content_loc4='找到生物 %u: %u' WHERE entry=441;
UPDATE trinity_string SET content_loc4='没有地区被发现!' WHERE entry=442;
UPDATE trinity_string SET content_loc4='没有找到物品集!' WHERE entry=443;
UPDATE trinity_string SET content_loc4='没有找到此技能!' WHERE entry=444;
UPDATE trinity_string SET content_loc4='没有找到此法术!' WHERE entry=445;
UPDATE trinity_string SET content_loc4='没有找到此任务!' WHERE entry=446;
UPDATE trinity_string SET content_loc4='没有找到此生物!' WHERE entry=447;
UPDATE trinity_string SET content_loc4='没有找到此游戏物品对象!' WHERE entry=448;
UPDATE trinity_string SET content_loc4='墓地 #%u 不存在.' WHERE entry=449;
UPDATE trinity_string SET content_loc4='墓地 #%u 已经连接到区域 #%u (当前).' WHERE entry=450;
UPDATE trinity_string SET content_loc4='墓地 #%u 连接到区域 #%u (当前).' WHERE entry=451;
UPDATE trinity_string SET content_loc4='墓地 #%u 不能连接到子区域或不存在的区域 #%u (内部错误).' WHERE entry=452;
UPDATE trinity_string SET content_loc4='没有阵营在墓地且 id= #%u , 请修复你的DB数据库' WHERE entry=454;
UPDATE trinity_string SET content_loc4='错误的队伍, 请修复你的数据库' WHERE entry=455;
UPDATE trinity_string SET content_loc4='任何' WHERE entry=456;
UPDATE trinity_string SET content_loc4='联盟' WHERE entry=457;
UPDATE trinity_string SET content_loc4='部落' WHERE entry=458;
UPDATE trinity_string SET content_loc4='墓地ID #%u (阵营faction: %s) 是最近的距此区域zoneID #%u.' WHERE entry=459;
UPDATE trinity_string SET content_loc4='区域Zone #%u 没有一个连接的墓地.' WHERE entry=460;
UPDATE trinity_string SET content_loc4='区域Zone #%u 没有一个连接的墓地为阵营faction: %s.' WHERE entry=461;
UPDATE trinity_string SET content_loc4='远距传物地点已经存在!' WHERE entry=462;
UPDATE trinity_string SET content_loc4='远距传送地点增加.' WHERE entry=463;
UPDATE trinity_string SET content_loc4='远距传送地点没增加: 数据库错误.' WHERE entry=464;
UPDATE trinity_string SET content_loc4='远距传送地点被删除.' WHERE entry=465;
UPDATE trinity_string SET content_loc4='No taxinodes found!' WHERE entry=466;
UPDATE trinity_string SET content_loc4='目标单位(unit)有 %d 光环auras:' WHERE entry=467;
UPDATE trinity_string SET content_loc4='id: %d effmask: %d charges: %d stack: %d slot %d duration: %d maxduration: %d' WHERE entry=468;
UPDATE trinity_string SET content_loc4='Target unit has %d auras of type %d:' WHERE entry=469;
UPDATE trinity_string SET content_loc4='id: %d eff: %d amount: %d' WHERE entry=470;
UPDATE trinity_string SET content_loc4='任务 %u 没有找到.' WHERE entry=471;
UPDATE trinity_string SET content_loc4='任务 %u 由物品触发. 为正确工作, 请, 添加物品到库里并且开始这个任务的正常方式: .additem %u' WHERE entry=472;
UPDATE trinity_string SET content_loc4='任务清除.' WHERE entry=473;
UPDATE trinity_string SET content_loc4=' [奖赏]' WHERE entry=474;
UPDATE trinity_string SET content_loc4=' [完成]' WHERE entry=475;
UPDATE trinity_string SET content_loc4=' [active]' WHERE entry=476;
UPDATE trinity_string SET content_loc4='%s 的飞行模式为 %s' WHERE entry=477;
UPDATE trinity_string SET content_loc4='操作代码Opcode %u 发送到(sent to) %s' WHERE entry=478;
UPDATE trinity_string SET content_loc4='角色加载成功!' WHERE entry=479;
UPDATE trinity_string SET content_loc4='加载角色失败!' WHERE entry=480;
UPDATE trinity_string SET content_loc4='卸载角色成功!' WHERE entry=481;
UPDATE trinity_string SET content_loc4='卸载角色失败!' WHERE entry=482;
UPDATE trinity_string SET content_loc4='魔法 %u 破裂，并且不允许使用或学习!' WHERE entry=483;
UPDATE trinity_string SET content_loc4='技能值 %u (%s) 为角色 %s 设置到 %u 并且当前最大设置到 %u (没有固定(天赋)奖励).' WHERE entry=484;
UPDATE trinity_string SET content_loc4='角色 %s 必须拥有技能 %u (%s) 在使用这个命令之前.' WHERE entry=485;
UPDATE trinity_string SET content_loc4='错误的技能 id (%u)' WHERE entry=486;
UPDATE trinity_string SET content_loc4='你学会了ＧＭ默认的法术和技能.' WHERE entry=487;
UPDATE trinity_string SET content_loc4='你已经学了这个法术.' WHERE entry=488;
UPDATE trinity_string SET content_loc4='目标Target(%s) 已经学习了那些法术.' WHERE entry=489;
UPDATE trinity_string SET content_loc4='%s 不懂那些法术.' WHERE entry=490;
UPDATE trinity_string SET content_loc4='您已经忘记了那个法术.' WHERE entry=491;
UPDATE trinity_string SET content_loc4='所有的法术冷却清除 for %s.' WHERE entry=492;
UPDATE trinity_string SET content_loc4='法术 %u 冷却清除 for %s.' WHERE entry=493;
UPDATE trinity_string SET content_loc4='命令: Additem, itemId = %i, amount = %i' WHERE entry=494;
UPDATE trinity_string SET content_loc4='命令: Additemset, itemsetId = %i' WHERE entry=495;
UPDATE trinity_string SET content_loc4='移除物品ID = %i, amount = %i from %s' WHERE entry=496;
UPDATE trinity_string SET content_loc4='不能创建物品  ''%i'' (数量amount: %i)' WHERE entry=497;
UPDATE trinity_string SET content_loc4='系统提示：你需要提供一个公会名字!' WHERE entry=498;
UPDATE trinity_string SET content_loc4='系统提示：玩家没有被找到!' WHERE entry=499;
UPDATE trinity_string SET content_loc4='系统提示：玩家已经有一个公会!' WHERE entry=500;
UPDATE trinity_string SET content_loc4='公会没被创建! (是否已经存在?)' WHERE entry=501;
UPDATE trinity_string SET content_loc4='没有物品从物品库 ''%u'' 里找到.' WHERE entry=502;
UPDATE trinity_string SET content_loc4='The distance is: (3D) %f (2D) %f (Exact 3D) %f (Exact 2D) %f yards.' WHERE entry=503;
UPDATE trinity_string SET content_loc4='物品 ''%i'' ''%s''  背包 %i' WHERE entry=504;
UPDATE trinity_string SET content_loc4='物品 ''%i'' 不存在.' WHERE entry=505;
UPDATE trinity_string SET content_loc4='物品 ''%i'' ''%s'' 已加入背包 %i' WHERE entry=506;
UPDATE trinity_string SET content_loc4='物品保存失败!' WHERE entry=507;
UPDATE trinity_string SET content_loc4='%d - owner: %s (guid: %u account: %u ) %s' WHERE entry=508;
UPDATE trinity_string SET content_loc4='%d - sender: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s' WHERE entry=509;
UPDATE trinity_string SET content_loc4='%d - owner: %s (guid: %u account: %u ) %s' WHERE entry=510;
UPDATE trinity_string SET content_loc4='Wrong link type!' WHERE entry=511;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r ' WHERE entry=512;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hquest:%d|h[%s]|h|r %s' WHERE entry=513;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' WHERE entry=514;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=515;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' WHERE entry=516;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=517;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' WHERE entry=518;
UPDATE trinity_string SET content_loc4='|cffffffff|Htele:%s|h[%s]|h|r ' WHERE entry=519;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hspell:%d|h[%s]|h|r ' WHERE entry=520;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s' WHERE entry=521;
UPDATE trinity_string SET content_loc4='Game Object (GUID: %u) not found' WHERE entry=522;
UPDATE trinity_string SET content_loc4='>> Game Object %s (GUID: %u) at %f %f %f. Orientation %f.' WHERE entry=523;
UPDATE trinity_string SET content_loc4='Selected object:
|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u
X: %f Y: %f Z: %f MapId: %u
Orientation: %f
Phasemask %u' WHERE entry=524;
UPDATE trinity_string SET content_loc4='>> Add Game Object ''%i'' (%s) (GUID: %i) added at ''%f %f %f''.' WHERE entry=525;
UPDATE trinity_string SET content_loc4='%s (lowguid: %u) movement generators stack:' WHERE entry=526;
UPDATE trinity_string SET content_loc4='   Idle' WHERE entry=527;
UPDATE trinity_string SET content_loc4='   Random' WHERE entry=528;
UPDATE trinity_string SET content_loc4='   Waypoint' WHERE entry=529;
UPDATE trinity_string SET content_loc4='   Animal random' WHERE entry=530;
UPDATE trinity_string SET content_loc4='   Confused' WHERE entry=531;
UPDATE trinity_string SET content_loc4='   Targeted to player %s (lowguid %u)' WHERE entry=532;
UPDATE trinity_string SET content_loc4='   Targeted to creature %s (lowguid %u)' WHERE entry=533;
UPDATE trinity_string SET content_loc4='   Targeted to <NULL>' WHERE entry=534;
UPDATE trinity_string SET content_loc4='   Home movement to (X:%f Y:%f Z:%f)' WHERE entry=535;
UPDATE trinity_string SET content_loc4='   Home movement used for player?!?' WHERE entry=536;
UPDATE trinity_string SET content_loc4='   Taxi flight' WHERE entry=537;
UPDATE trinity_string SET content_loc4='   Unknown movement generator (%u)' WHERE entry=538;
UPDATE trinity_string SET content_loc4='Player selected NPC
GUID: %u.
Faction: %u.
npcFlags: %u.
Entry: %u.
DisplayID: %u (Native: %u).' WHERE entry=539;
UPDATE trinity_string SET content_loc4='等级: %u.' WHERE entry=540;
UPDATE trinity_string SET content_loc4='Health (base): %u. (max): %u. (current): %u.' WHERE entry=541;
UPDATE trinity_string SET content_loc4='Field Flags: %u.
Dynamic Flags: %u.
Faction Template: %u.' WHERE entry=542;
UPDATE trinity_string SET content_loc4='Loot: %u Pickpocket: %u Skinning: %u' WHERE entry=543;
UPDATE trinity_string SET content_loc4='Position: %f %f %f.' WHERE entry=544;
UPDATE trinity_string SET content_loc4='*** 是一个销售师!' WHERE entry=545;
UPDATE trinity_string SET content_loc4='*** 是一个训练师!' WHERE entry=546;
UPDATE trinity_string SET content_loc4='副本ID: %u' WHERE entry=547;
UPDATE trinity_string SET content_loc4='玩家%s %s (guid: %u) 帐号: %s (id: %u) G M等级: %u 最后IP: %s 最后登陆: %s Latency: %ums' WHERE entry=548;
UPDATE trinity_string SET content_loc4='已登录时间: %s 等级: %u 金钱: %ug%us%uc' WHERE entry=549;
UPDATE trinity_string SET content_loc4='Ban time remaining: %s, Banned by: %s, Reason: %s' WHERE entry=453;
UPDATE trinity_string SET content_loc4='%s 探索了所有地区.' WHERE entry=551;
UPDATE trinity_string SET content_loc4='%s 没有更多的探索区.' WHERE entry=552;
UPDATE trinity_string SET content_loc4='%s 你探索了所有地带.' WHERE entry=553;
UPDATE trinity_string SET content_loc4='%s 你掩藏了所有区域.' WHERE entry=554;
UPDATE trinity_string SET content_loc4='悬停启用' WHERE entry=555;
UPDATE trinity_string SET content_loc4='Hover disabled' WHERE entry=556;
UPDATE trinity_string SET content_loc4='%s level up you to (%i)' WHERE entry=557;
UPDATE trinity_string SET content_loc4='%s level down you to (%i)' WHERE entry=558;
UPDATE trinity_string SET content_loc4='%s reset your level progress.' WHERE entry=559;
UPDATE trinity_string SET content_loc4='该地区已被定为探索.' WHERE entry=560;
UPDATE trinity_string SET content_loc4='区域被设置了依照没被探索.' WHERE entry=561;
UPDATE trinity_string SET content_loc4='GUID=%i ''s updateIndex: %i, value:  %i.' WHERE entry=562;
UPDATE trinity_string SET content_loc4='You change GUID=%i ''s UpdateIndex: %i value to %i.' WHERE entry=563;
UPDATE trinity_string SET content_loc4='The value index %u is too big to %u(count: %u).' WHERE entry=564;
UPDATE trinity_string SET content_loc4='Set %u uint32 Value:[OPCODE]:%u [VALUE]:%u' WHERE entry=565;
UPDATE trinity_string SET content_loc4='You Set %u Field:%u to uint32 Value: %u' WHERE entry=566;
UPDATE trinity_string SET content_loc4='Set %u float Value:[OPCODE]:%u [VALUE]:%f' WHERE entry=567;
UPDATE trinity_string SET content_loc4='You Set %u Field:%i to float Value: %f' WHERE entry=568;
UPDATE trinity_string SET content_loc4='Get %u uint32 Value:[OPCODE]:%u [VALUE]:%u' WHERE entry=569;
UPDATE trinity_string SET content_loc4='The uint32 value of %u in %u is: %u' WHERE entry=570;
UPDATE trinity_string SET content_loc4='Get %u float Value:[OPCODE]:%u [VALUE]:%f' WHERE entry=571;
UPDATE trinity_string SET content_loc4='The float of %u value in %u is: %f' WHERE entry=572;
UPDATE trinity_string SET content_loc4='.Set32Bit:[OPCODE]:%u [VALUE]:%u' WHERE entry=573;
UPDATE trinity_string SET content_loc4='You set Bit of Field:%u to Value: %u' WHERE entry=574;
UPDATE trinity_string SET content_loc4='.Mod32Value:[OPCODE]:%u [VALUE]:%i' WHERE entry=575;
UPDATE trinity_string SET content_loc4='You modified the value of Field:%u to Value: %u' WHERE entry=576;
UPDATE trinity_string SET content_loc4='你现在处于隐身状态.' WHERE entry=577;
UPDATE trinity_string SET content_loc4='你现在处于可见状态.' WHERE entry=578;
UPDATE trinity_string SET content_loc4='Selected player or creature not have victim.' WHERE entry=579;
UPDATE trinity_string SET content_loc4='玩家 %s 学会了所有的本种族本职业的魔法,包括任何奖励的技能.' WHERE entry=580;
UPDATE trinity_string SET content_loc4='Found near gameobjects (distance %f): %u ' WHERE entry=581;
UPDATE trinity_string SET content_loc4='SpawnTime: Full:%s Remain:%s' WHERE entry=582;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE entry=583;
UPDATE trinity_string SET content_loc4='没有事件被找到!' WHERE entry=584;
UPDATE trinity_string SET content_loc4='事件不存在!' WHERE entry=585;
UPDATE trinity_string SET content_loc4='事件 %u: %s%s
开始: %s 结束: %s 发生: %s 全程: %s
下一次状态改变: %s' WHERE entry=586;
UPDATE trinity_string SET content_loc4='事件 %u 已经开始!' WHERE entry=587;
UPDATE trinity_string SET content_loc4='事件 %u 没有开始!' WHERE entry=588;
UPDATE trinity_string SET content_loc4='   Point movement to (X:%f Y:%f Z:%f)' WHERE entry=589;
UPDATE trinity_string SET content_loc4='   Fear movement' WHERE entry=590;
UPDATE trinity_string SET content_loc4='   Distract movement' WHERE entry=591;
UPDATE trinity_string SET content_loc4='You have learned all spells in craft: %s' WHERE entry=592;
UPDATE trinity_string SET content_loc4='Currently Banned Accounts:' WHERE entry=593;
UPDATE trinity_string SET content_loc4='|    Account    |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |' WHERE entry=594;
UPDATE trinity_string SET content_loc4='Currently Banned IPs:' WHERE entry=595;
UPDATE trinity_string SET content_loc4='|      IP       |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |' WHERE entry=596;
UPDATE trinity_string SET content_loc4='Current gamemasters:' WHERE entry=597;
UPDATE trinity_string SET content_loc4='|    Account    |  GM  |' WHERE entry=598;
UPDATE trinity_string SET content_loc4='No gamemasters.' WHERE entry=599;
UPDATE trinity_string SET content_loc4='联盟获得胜利!' WHERE entry=600;
UPDATE trinity_string SET content_loc4='部落获得胜利!' WHERE entry=601;
UPDATE trinity_string SET content_loc4='战场战歌峡谷争夺1分钟倒计时中...' WHERE entry=602;
UPDATE trinity_string SET content_loc4='战场战歌峡谷争夺，在30秒后开始。大家做好准备!' WHERE entry=603;
UPDATE trinity_string SET content_loc4='战场战歌峡谷争夺正式开始!' WHERE entry=604;
UPDATE trinity_string SET content_loc4='$n 夺取了部落旗子!' WHERE entry=605;
UPDATE trinity_string SET content_loc4='$n 夺取了联盟旗子!' WHERE entry=606;
UPDATE trinity_string SET content_loc4='部落旗子被 $n 降下!' WHERE entry=607;
UPDATE trinity_string SET content_loc4='联盟旗子被 $n 降下!' WHERE entry=608;
UPDATE trinity_string SET content_loc4='联盟旗子被 $n 返回了到它的基地!' WHERE entry=609;
UPDATE trinity_string SET content_loc4='部落旗子被 $n 返回了到它的基地!' WHERE entry=610;
UPDATE trinity_string SET content_loc4='部落旗子被 $n 拾起!' WHERE entry=611;
UPDATE trinity_string SET content_loc4='魔兽世界：联盟旗子被 $n 拾起!' WHERE entry=612;
UPDATE trinity_string SET content_loc4='旗子现在被安置在他们的基地.' WHERE entry=613;
UPDATE trinity_string SET content_loc4='联盟旗帜已经被重置' WHERE entry=614;
UPDATE trinity_string SET content_loc4='联盟旗帜已经被重置!' WHERE entry=615;
UPDATE trinity_string SET content_loc4='战场暴风之眼争夺1分钟倒计时中....' WHERE entry=636;
UPDATE trinity_string SET content_loc4='战场暴风之眼争夺，在30秒后开始。大家做好准备!.' WHERE entry=637;
UPDATE trinity_string SET content_loc4='战场暴风之眼争夺正式开始!!' WHERE entry=638;
UPDATE trinity_string SET content_loc4='联盟' WHERE entry=650;
UPDATE trinity_string SET content_loc4='部落' WHERE entry=651;
UPDATE trinity_string SET content_loc4='stables' WHERE entry=652;
UPDATE trinity_string SET content_loc4='blacksmith' WHERE entry=653;
UPDATE trinity_string SET content_loc4='farm' WHERE entry=654;
UPDATE trinity_string SET content_loc4='lumber mill' WHERE entry=655;
UPDATE trinity_string SET content_loc4='mine' WHERE entry=656;
UPDATE trinity_string SET content_loc4='此 %s 采取了 %s' WHERE entry=657;
UPDATE trinity_string SET content_loc4='$n 保卫了  %s' WHERE entry=658;
UPDATE trinity_string SET content_loc4='$n 攻击了  %s' WHERE entry=659;
UPDATE trinity_string SET content_loc4='$n 主持这个 %s 吧! 如果听之任之, 这个 %s 将在1 分钟之内控制它!' WHERE entry=660;
UPDATE trinity_string SET content_loc4='战场阿拉西盆地争夺1分钟倒计时中...' WHERE entry=661;
UPDATE trinity_string SET content_loc4='战场阿拉西盆地争夺，在30秒后开始。大家做好准备!' WHERE entry=662;
UPDATE trinity_string SET content_loc4='战场阿拉西盆地争夺正式开始!' WHERE entry=663;
UPDATE trinity_string SET content_loc4='联盟已收集到$1776W资源, 并已接近胜利!' WHERE entry=664;
UPDATE trinity_string SET content_loc4='部落已收集到$1777W资源, 并已接近胜利!' WHERE entry=665;
UPDATE trinity_string SET content_loc4='你在最近的 %s 战斗之后,我们努力想为你颁发一个荣誉标志却没有成功,结束后你会发现这个荣誉标志的,但不是此刻,感谢你在 %s 的战斗.' WHERE entry=666;
UPDATE trinity_string SET content_loc4='The Alliance has taken control of the Mage Tower!' WHERE entry=667;
UPDATE trinity_string SET content_loc4='The Horde has taken control of the Mage Tower!' WHERE entry=668;
UPDATE trinity_string SET content_loc4='The Alliance has taken control of the Draenei Ruins!' WHERE entry=669;
UPDATE trinity_string SET content_loc4='The Horde has taken control of the Draenei Ruins!' WHERE entry=670;
UPDATE trinity_string SET content_loc4='The Alliance has taken control of the Blood Elf Tower!' WHERE entry=671;
UPDATE trinity_string SET content_loc4='The Horde has taken control of the Blood Elf Tower!' WHERE entry=672;
UPDATE trinity_string SET content_loc4='The Alliance has taken control of the Fel Reaver Ruins!' WHERE entry=673;
UPDATE trinity_string SET content_loc4='The Horde has taken control of the Fel Reaver Ruins!' WHERE entry=674;
UPDATE trinity_string SET content_loc4='The Alliance has lost control of the Mage Tower!' WHERE entry=675;
UPDATE trinity_string SET content_loc4='The Horde has lost control of the Mage Tower!' WHERE entry=676;
UPDATE trinity_string SET content_loc4='The Alliance has lost control of the Draenei Ruins!' WHERE entry=677;
UPDATE trinity_string SET content_loc4='The Horde has lost control of the Draenei Ruins!' WHERE entry=678;
UPDATE trinity_string SET content_loc4='The Alliance has lost control of the Blood Elf Tower!' WHERE entry=679;
UPDATE trinity_string SET content_loc4='The Horde has lost control of the Blood Elf Tower!' WHERE entry=680;
UPDATE trinity_string SET content_loc4='The Alliance has lost control of the Fel Reaver Ruins!' WHERE entry=681;
UPDATE trinity_string SET content_loc4='The Horde has lost control of the Fel Reaver Ruins!' WHERE entry=682;
UPDATE trinity_string SET content_loc4='$N has taken the flag!' WHERE entry=683;
UPDATE trinity_string SET content_loc4='The Alliance has captured the flag!' WHERE entry=684;
UPDATE trinity_string SET content_loc4='The Horde has captured the flag!' WHERE entry=685;
UPDATE trinity_string SET content_loc4='旗子已经被降下!' WHERE entry=686;
UPDATE trinity_string SET content_loc4='旗帜已经被重置' WHERE entry=687;
UPDATE trinity_string SET content_loc4='你必须达到等级  %u 才能进入竞技场.' WHERE entry=700;
UPDATE trinity_string SET content_loc4='一分钟后竞技场争斗开始!' WHERE entry=701;
UPDATE trinity_string SET content_loc4='三十秒后竞技场争斗开始!' WHERE entry=702;
UPDATE trinity_string SET content_loc4='十五秒后竞技场争斗开始!' WHERE entry=703;
UPDATE trinity_string SET content_loc4='竞技场争斗开始了!' WHERE entry=704;
UPDATE trinity_string SET content_loc4='你必须等待 %s 才能继续喊话.' WHERE entry=705;
UPDATE trinity_string SET content_loc4='这些道具在装备/存放中出现一个问题.' WHERE entry=706;
UPDATE trinity_string SET content_loc4='%s 免打扰状态下无法收到悄悄话: %s' WHERE entry=707;
UPDATE trinity_string SET content_loc4='%s 不在机器旁: %s' WHERE entry=708;
UPDATE trinity_string SET content_loc4='请勿打扰' WHERE entry=709;
UPDATE trinity_string SET content_loc4='不在机器旁' WHERE entry=710;
UPDATE trinity_string SET content_loc4='Queue status for %s (Lvl: %u to %u)
Queued alliances: %u (Need at least %u more)
Queued hordes: %u (Need at least %u more)' WHERE entry=711;
UPDATE trinity_string SET content_loc4='|cffff0000[战场公告]:|r %s -- [%u-%u] 联盟: 目前%u人 (需: %u人), 部落: 目前%u人 (需: %u人)|r' WHERE entry=712;
UPDATE trinity_string SET content_loc4='你的等级必须达到 %u 才能加入一个竞技场队伍!' WHERE entry=713;
UPDATE trinity_string SET content_loc4='不能达到进入战场的要求.' WHERE entry=715;
UPDATE trinity_string SET content_loc4='|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] Started!|r' WHERE entry=717;
UPDATE trinity_string SET content_loc4='|cffff0000[Arena Queue Announcer]:|r %s -- Joined : %ux%u : %u|r' WHERE entry=718;
UPDATE trinity_string SET content_loc4='|cffff0000[Arena Queue Announcer]:|r %s -- Exited : %ux%u : %u|r' WHERE entry=719;
UPDATE trinity_string SET content_loc4='Your group is too large for this battleground. Please regroup to join.' WHERE entry=720;
UPDATE trinity_string SET content_loc4='Your group is too large for this arena. Please regroup to join.' WHERE entry=721;
UPDATE trinity_string SET content_loc4='Your group has members not in your arena team. Please regroup to join.' WHERE entry=722;
UPDATE trinity_string SET content_loc4='Your group does not have enough players to join this match.' WHERE entry=723;
UPDATE trinity_string SET content_loc4='The Gold Team wins!' WHERE entry=724;
UPDATE trinity_string SET content_loc4='The Green Team wins!' WHERE entry=725;
UPDATE trinity_string SET content_loc4='There aren''t enough players in this battleground. It will end soon unless some more players join to balance the fight.' WHERE entry=726;
UPDATE trinity_string SET content_loc4='Your group has an offline member. Please remove him before joining.' WHERE entry=727;
UPDATE trinity_string SET content_loc4='Your group has players from the opposing faction. You can''t join the battleground as a group.' WHERE entry=728;
UPDATE trinity_string SET content_loc4='Your group has players from different battleground brakets. You can''t join as group.' WHERE entry=729;
UPDATE trinity_string SET content_loc4='Someone in your party is already in this battleground queue. (S)he must leave it before joining as group.' WHERE entry=730;
UPDATE trinity_string SET content_loc4='Someone in your party is Deserter. You can''t join as group.' WHERE entry=731;
UPDATE trinity_string SET content_loc4='Someone in your party is already in three battleground queues. You cannot join as group.' WHERE entry=732;
UPDATE trinity_string SET content_loc4='You cannot teleport to a battleground or arena map.' WHERE entry=733;
UPDATE trinity_string SET content_loc4='You cannot summon players to a battleground or arena map.' WHERE entry=734;
UPDATE trinity_string SET content_loc4='You must be in GM mode to teleport to a player in a battleground.' WHERE entry=735;
UPDATE trinity_string SET content_loc4='You cannot teleport to a battleground from another battleground. Please leave the current battleground first.' WHERE entry=736;
UPDATE trinity_string SET content_loc4='Arenas are set to 1v1 for debugging. So, don''t join as group.' WHERE entry=737;
UPDATE trinity_string SET content_loc4='Arenas are set to normal playercount.' WHERE entry=738;
UPDATE trinity_string SET content_loc4='单人战场开启.战场设置（1V0）.' WHERE entry=739;
UPDATE trinity_string SET content_loc4='战场模式已更改为：正常状态.' WHERE entry=740;
UPDATE trinity_string SET content_loc4='Flushing Arena points based on team ratings, this may take a few minutes. Please stand by...' WHERE entry=741;
UPDATE trinity_string SET content_loc4='Distributing arena points to players...' WHERE entry=742;
UPDATE trinity_string SET content_loc4='Finished setting arena points for online players.' WHERE entry=743;
UPDATE trinity_string SET content_loc4='Modifying played count, arena points etc. for loaded arena teams, sending updated stats to online players...' WHERE entry=744;
UPDATE trinity_string SET content_loc4='Modification done.' WHERE entry=745;
UPDATE trinity_string SET content_loc4='Done flushing Arena points.' WHERE entry=746;
UPDATE trinity_string SET content_loc4='linkGUID: %u, Entry: %u (%s)' WHERE entry=750;
UPDATE trinity_string SET content_loc4='Not enough players. This game will close in %u seconds.' WHERE entry=751;
UPDATE trinity_string SET content_loc4='The battle for Warsong Gulch begins in 2 minutes.' WHERE entry=753;
UPDATE trinity_string SET content_loc4='The battle for Arathi Basin begins in 2 minutes.' WHERE entry=754;
UPDATE trinity_string SET content_loc4='The battle for Eye of the Storm begins in 2 minutes.' WHERE entry=755;
UPDATE trinity_string SET content_loc4='Current selected title for player %s reset as not known now.' WHERE entry=356;
UPDATE trinity_string SET content_loc4='Title %u (%s) set as current seelcted title for player %s.' WHERE entry=355;
UPDATE trinity_string SET content_loc4='Title %u (%s) removed from known titles list for player %s.' WHERE entry=354;
UPDATE trinity_string SET content_loc4='%d (idx:%d) - [%s %s] %s %s ' WHERE entry=350;
UPDATE trinity_string SET content_loc4='No titles found!' WHERE entry=351;
UPDATE trinity_string SET content_loc4='Invalid title id: %u' WHERE entry=352;
UPDATE trinity_string SET content_loc4='Title %u (%s) added to known titles list for player %s.' WHERE entry=353;
UPDATE trinity_string SET content_loc4='%d (idx:%d) - |cffffffff|Htitle:%d|h[%s %s]|h|r %s %s ' WHERE entry=349;
UPDATE trinity_string SET content_loc4='Arena testing turned %s' WHERE entry=785;
UPDATE trinity_string SET content_loc4='|cffff0000[Automatic]:|r' WHERE entry=786;
UPDATE trinity_string SET content_loc4='|cffffff00[|c1f40af20Announce by|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry=787;
UPDATE trinity_string SET content_loc4='Invalid name' WHERE entry=800;
UPDATE trinity_string SET content_loc4='You do not have enough gold' WHERE entry=801;
UPDATE trinity_string SET content_loc4='You do not have enough free slots' WHERE entry=802;
UPDATE trinity_string SET content_loc4='Your partner does not have enough free bag slots' WHERE entry=803;
UPDATE trinity_string SET content_loc4='You do not have permission to perform that function' WHERE entry=804;
UPDATE trinity_string SET content_loc4='未知的语言' WHERE entry=805;
UPDATE trinity_string SET content_loc4='You don''t know that language' WHERE entry=806;
UPDATE trinity_string SET content_loc4='Please provide character name' WHERE entry=807;
UPDATE trinity_string SET content_loc4='Player %s not found or offline' WHERE entry=808;
UPDATE trinity_string SET content_loc4='Account for character %s not found' WHERE entry=809;
UPDATE trinity_string SET content_loc4='|Hplayer:$N|h[$N]|h 获得了成就 $a!' WHERE entry=810;
UPDATE trinity_string SET content_loc4='公会管理员' WHERE entry=811;
UPDATE trinity_string SET content_loc4='官员' WHERE entry=812;
UPDATE trinity_string SET content_loc4='精英' WHERE entry=813;
UPDATE trinity_string SET content_loc4='会员' WHERE entry=814;
UPDATE trinity_string SET content_loc4='新人' WHERE entry=815;
UPDATE trinity_string SET content_loc4='Warning: You''ve entered a no-fly zone and are about to be dismounted!' WHERE entry=816;
UPDATE trinity_string SET content_loc4='Exiting daemon...' WHERE entry=1000;
UPDATE trinity_string SET content_loc4='Account deleted: %s' WHERE entry=1001;
UPDATE trinity_string SET content_loc4='Account %s NOT deleted (probably sql file format was updated)' WHERE entry=1002;
UPDATE trinity_string SET content_loc4='Account %s NOT deleted (unknown error)' WHERE entry=1003;
UPDATE trinity_string SET content_loc4='Account created: %s' WHERE entry=1004;
UPDATE trinity_string SET content_loc4='Account name can''t be longer than 16 characters (client limit), account not created!' WHERE entry=1005;
UPDATE trinity_string SET content_loc4='Account with this name already exist!' WHERE entry=1006;
UPDATE trinity_string SET content_loc4='Account %s NOT created (probably sql file format was updated)' WHERE entry=1007;
UPDATE trinity_string SET content_loc4='Account %s NOT created (unknown error)' WHERE entry=1008;
UPDATE trinity_string SET content_loc4='Player %s (Guid: %u) Account %s (Id: %u) deleted.' WHERE entry=1009;
UPDATE trinity_string SET content_loc4='|<Error>        | %20s |<Error>          |<Er>| <Error>   |' WHERE entry=1011;
UPDATE trinity_string SET content_loc4='|    Account    |       Character      |       IP        | GM | Expansion |' WHERE entry=1010;
UPDATE trinity_string SET content_loc4='No online players.' WHERE entry=1014;
UPDATE trinity_string SET content_loc4='Account %s (Id: %u) have up to %u expansion allowed now.' WHERE entry=1100;
UPDATE trinity_string SET content_loc4='Message of the day changed to:
%s' WHERE entry=1101;
UPDATE trinity_string SET content_loc4='Message sent to %s: %s' WHERE entry=1102;
UPDATE trinity_string SET content_loc4='%d - %s %s' WHERE entry=1103;
UPDATE trinity_string SET content_loc4='%d - %s' WHERE entry=1104;
UPDATE trinity_string SET content_loc4='%d - %s' WHERE entry=1105;
UPDATE trinity_string SET content_loc4='%d - %s %s' WHERE entry=1106;
UPDATE trinity_string SET content_loc4='%d - %s' WHERE entry=1107;
UPDATE trinity_string SET content_loc4='%d - %s %s' WHERE entry=1108;
UPDATE trinity_string SET content_loc4='%d - %s %s %s' WHERE entry=1109;
UPDATE trinity_string SET content_loc4='%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1110;
UPDATE trinity_string SET content_loc4='%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1111;
UPDATE trinity_string SET content_loc4='Failed to open file: %s' WHERE entry=1112;
UPDATE trinity_string SET content_loc4='Account %s (%u) have max amount allowed characters (client limit)' WHERE entry=1113;
UPDATE trinity_string SET content_loc4='Dump file have broken data!' WHERE entry=1114;
UPDATE trinity_string SET content_loc4='Invalid character name!' WHERE entry=1115;
UPDATE trinity_string SET content_loc4='Invalid character guid!' WHERE entry=1116;
UPDATE trinity_string SET content_loc4='Character guid %u in use!' WHERE entry=1117;
UPDATE trinity_string SET content_loc4='%d - guild: %s (guid: %u) %s' WHERE entry=1118;
UPDATE trinity_string SET content_loc4='You must use male or female as gender.' WHERE entry=1119;
UPDATE trinity_string SET content_loc4='You change gender of %s to %s.' WHERE entry=1120;
UPDATE trinity_string SET content_loc4='Your gender changed to %s by %s.' WHERE entry=1121;
UPDATE trinity_string SET content_loc4='Your group is too large for this battleground. Please regroup to join.' WHERE entry=1122;
UPDATE trinity_string SET content_loc4='没有找到宠物。' WHERE entry=1123;
UPDATE trinity_string SET content_loc4='错误的宠物类型。' WHERE entry=1124;
UPDATE trinity_string SET content_loc4='Your pet learned all talents' WHERE entry=1125;
UPDATE trinity_string SET content_loc4='Your pet talents have been reset.' WHERE entry=1126;
UPDATE trinity_string SET content_loc4='Talents of %s''s pet reset.' WHERE entry=1127;
UPDATE trinity_string SET content_loc4='%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1128;
UPDATE trinity_string SET content_loc4='%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1129;
UPDATE trinity_string SET content_loc4='You try to view cinemitic %u but it doesn''t exist.' WHERE entry=1200;
UPDATE trinity_string SET content_loc4='You try to view movie %u but it doesn''t exist.' WHERE entry=1201;
UPDATE trinity_string SET content_loc4='联盟' WHERE entry=1300;
UPDATE trinity_string SET content_loc4='部落' WHERE entry=1301;
UPDATE trinity_string SET content_loc4='%s was destroyed by the %s!' WHERE entry=1302;
UPDATE trinity_string SET content_loc4='The %s is under attack! If left unchecked, the %s will destroy it!' WHERE entry=1303;
UPDATE trinity_string SET content_loc4='The %s was taken by the %s!' WHERE entry=1304;
UPDATE trinity_string SET content_loc4='The %s was taken by the %s!' WHERE entry=1305;
UPDATE trinity_string SET content_loc4='The %s was taken by the %s!' WHERE entry=1306;
UPDATE trinity_string SET content_loc4='The %s is under attack! If left unchecked, the %s will capture it!' WHERE entry=1307;
UPDATE trinity_string SET content_loc4='The %s has taken the %s! Its supplies will now be used for reinforcements!' WHERE entry=1308;
UPDATE trinity_string SET content_loc4='Irondeep Mine' WHERE entry=1309;
UPDATE trinity_string SET content_loc4='Coldtooth Mine' WHERE entry=1310;
UPDATE trinity_string SET content_loc4='Stormpike Aid Station' WHERE entry=1311;
UPDATE trinity_string SET content_loc4='Dun Baldar South Bunker' WHERE entry=1312;
UPDATE trinity_string SET content_loc4='Dun Baldar North Bunker' WHERE entry=1313;
UPDATE trinity_string SET content_loc4='Stormpike Graveyard' WHERE entry=1314;
UPDATE trinity_string SET content_loc4='Icewing Bunker' WHERE entry=1315;
UPDATE trinity_string SET content_loc4='Stonehearth Graveyard' WHERE entry=1316;
UPDATE trinity_string SET content_loc4='Stonehearth Bunker' WHERE entry=1317;
UPDATE trinity_string SET content_loc4='Snowfall Graveyard' WHERE entry=1318;
UPDATE trinity_string SET content_loc4='Iceblood Tower' WHERE entry=1319;
UPDATE trinity_string SET content_loc4='Iceblood Graveyard' WHERE entry=1320;
UPDATE trinity_string SET content_loc4='Tower Point' WHERE entry=1321;
UPDATE trinity_string SET content_loc4='Frostwolf Graveyard' WHERE entry=1322;
UPDATE trinity_string SET content_loc4='East Frostwolf Tower' WHERE entry=1323;
UPDATE trinity_string SET content_loc4='West Frostwolf Tower' WHERE entry=1324;
UPDATE trinity_string SET content_loc4='Frostwolf Relief Hut' WHERE entry=1325;
UPDATE trinity_string SET content_loc4='The Battle for Alterac Valley begins in 1 minute.' WHERE entry=1326;
UPDATE trinity_string SET content_loc4='The Battle for Alterac Valley begins in 30 seconds. Prepare yourselves!' WHERE entry=1327;
UPDATE trinity_string SET content_loc4='The Battle for Alterac Valley has begun!' WHERE entry=1328;
UPDATE trinity_string SET content_loc4='The Alliance Team is running out of reinforcements!' WHERE entry=1329;
UPDATE trinity_string SET content_loc4='The Horde Team is running out of reinforcements!' WHERE entry=1330;
UPDATE trinity_string SET content_loc4='The Frostwolf General is Dead!' WHERE entry=1331;
UPDATE trinity_string SET content_loc4='The Stormpike General is Dead!' WHERE entry=1332;
UPDATE trinity_string SET content_loc4='The Battle for Alterac Valley begins in 2 minutes.' WHERE entry=1333;
UPDATE trinity_string SET content_loc4='|cff00ff00New ticket from|r|cffff00ff %s.|r |cff00ff00Ticket entry:|r|cffff00ff %d.|r' WHERE entry=2000;
UPDATE trinity_string SET content_loc4='|cff00ff00Character|r|cffff00ff %s |r|cff00ff00edited his/her ticket:|r|cffff00ff %d.|r' WHERE entry=2001;
UPDATE trinity_string SET content_loc4='|cff00ff00Character|r|cffff00ff %s |r|cff00ff00abandoned ticket entry:|r|cffff00ff %d.|r' WHERE entry=2002;
UPDATE trinity_string SET content_loc4='|cff00ff00Closed by|r:|cff00ccff %s|r ' WHERE entry=2003;
UPDATE trinity_string SET content_loc4='|cff00ff00Deleted by|r:|cff00ccff %s|r ' WHERE entry=2004;
UPDATE trinity_string SET content_loc4='Ticket not found.' WHERE entry=2005;
UPDATE trinity_string SET content_loc4='Please close ticket before deleting it permanently.' WHERE entry=2006;
UPDATE trinity_string SET content_loc4='Ticket %d is already assigned.' WHERE entry=2007;
UPDATE trinity_string SET content_loc4='%u Tickets succesfully reloaded from the database.' WHERE entry=2008;
UPDATE trinity_string SET content_loc4='Showing list of open tickets.' WHERE entry=2009;
UPDATE trinity_string SET content_loc4='Showing list of open tickets whose creator is online.' WHERE entry=2010;
UPDATE trinity_string SET content_loc4='Showing list of closed tickets.' WHERE entry=2011;
UPDATE trinity_string SET content_loc4='Invalid name specified. Name should be that of an online Gamemaster.' WHERE entry=2012;
UPDATE trinity_string SET content_loc4='This ticket is already assigned to yourself. To unassign use .ticket unassign %d and then reassign.' WHERE entry=2013;
UPDATE trinity_string SET content_loc4='Ticket %d is not assigned, you cannot unassign it.' WHERE entry=2014;
UPDATE trinity_string SET content_loc4='You cannot unassign tickets from staffmembers with a higher security level than yourself.' WHERE entry=2015;
UPDATE trinity_string SET content_loc4='Cannot close ticket %d, it is assigned to another GM.' WHERE entry=2016;
UPDATE trinity_string SET content_loc4='
|cff00ff00Comment|r: "%s"|r ' WHERE entry=2023;
UPDATE trinity_string SET content_loc4='|cff00ff00Created by|r:|cff00ccff %s|r ' WHERE entry=2018;
UPDATE trinity_string SET content_loc4='|cff00ff00Last change|r:|cff00ccff %s ago|r ' WHERE entry=2019;
UPDATE trinity_string SET content_loc4='|cff00ff00Assigned to|r:|cff00ccff %s|r ' WHERE entry=2020;
UPDATE trinity_string SET content_loc4='|cff00ff00Unassigned by|r:|cff00ccff %s|r ' WHERE entry=2021;
UPDATE trinity_string SET content_loc4='
|cff00ff00Message|r: "%s"|r ' WHERE entry=2022;
UPDATE trinity_string SET content_loc4='|cff00ff00Ticket|r:|cff00ccff %d.|r ' WHERE entry=2017;
UPDATE trinity_string SET content_loc4='|cff00ff00Created|r:|cff00ccff %s ago|r ' WHERE entry=2025;
UPDATE trinity_string SET content_loc4='You froze player %s.' WHERE entry=5000;
UPDATE trinity_string SET content_loc4='It might be amusing but no... you cant freeze yourself!' WHERE entry=5001;
UPDATE trinity_string SET content_loc4='Invalid input check the name of target.' WHERE entry=5002;
UPDATE trinity_string SET content_loc4='You unfroze player %s.' WHERE entry=5003;
UPDATE trinity_string SET content_loc4='There are no frozen players.' WHERE entry=5004;
UPDATE trinity_string SET content_loc4='Following players are frozen on the server:' WHERE entry=5005;
UPDATE trinity_string SET content_loc4='- %s' WHERE entry=5006;
UPDATE trinity_string SET content_loc4='你必须在一个团队中才能进入此副本.' WHERE entry=5007;
UPDATE trinity_string SET content_loc4='开始在服务器播放音乐: %u ' WHERE entry=5009;
UPDATE trinity_string SET content_loc4='linkGUID: %u, Entry: %u (%s)' WHERE entry=5010;
UPDATE trinity_string SET content_loc4='You can''t teleport self to self!' WHERE entry=5011;
UPDATE trinity_string SET content_loc4='没有找到地图!' WHERE entry=5012;
UPDATE trinity_string SET content_loc4='[Continent]' WHERE entry=5013;
UPDATE trinity_string SET content_loc4='[Instance]' WHERE entry=5014;
UPDATE trinity_string SET content_loc4='[Battleground]' WHERE entry=5015;
UPDATE trinity_string SET content_loc4='[竞技场]' WHERE entry=5016;
UPDATE trinity_string SET content_loc4='[副本重置时间: %s]' WHERE entry=5017;
UPDATE trinity_string SET content_loc4='[地下城重置时间: %s]' WHERE entry=5018;
UPDATE trinity_string SET content_loc4='[Mountable]' WHERE entry=5019;
UPDATE trinity_string SET content_loc4='|cfff00000[GM Announcement]: %s|r' WHERE entry=6613;
UPDATE trinity_string SET content_loc4='Notification to GM''s - ' WHERE entry=6614;
UPDATE trinity_string SET content_loc4='|cffffff00[|c1f40af20GM Announce by|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry=6615;
UPDATE trinity_string SET content_loc4='Pet spells will reset for all players at login. Strongly recommend re-login!' WHERE entry=6616;
UPDATE trinity_string SET content_loc4='WORLD: Denying connections.' WHERE entry=7523;
UPDATE trinity_string SET content_loc4='WORLD: Accepting connections.' WHERE entry=7524;
UPDATE trinity_string SET content_loc4='The Horde has taken The Overlook!' WHERE entry=10001;
UPDATE trinity_string SET content_loc4='The Alliance has taken The Overlook!' WHERE entry=10002;
UPDATE trinity_string SET content_loc4='The Horde has taken The Stadium!' WHERE entry=10003;
UPDATE trinity_string SET content_loc4='The Alliance has taken The Stadium!' WHERE entry=10004;
UPDATE trinity_string SET content_loc4='The Horde has taken Broken Hill!' WHERE entry=10005;
UPDATE trinity_string SET content_loc4='The Alliance has taken Broken Hill!' WHERE entry=10006;
UPDATE trinity_string SET content_loc4='The Horde lost The Overlook!' WHERE entry=10007;
UPDATE trinity_string SET content_loc4='The Alliance lost The Overlook!' WHERE entry=10008;
UPDATE trinity_string SET content_loc4='The Horde lost The Stadium!' WHERE entry=10009;
UPDATE trinity_string SET content_loc4='The Alliance lost The Stadium!' WHERE entry=10010;
UPDATE trinity_string SET content_loc4='The Horde lost Broken Hill!' WHERE entry=10011;
UPDATE trinity_string SET content_loc4='The Alliance lost Broken Hill!' WHERE entry=10012;
UPDATE trinity_string SET content_loc4='The Horde has taken the West Beacon!' WHERE entry=10013;
UPDATE trinity_string SET content_loc4='The Alliance has taken the West Beacon!' WHERE entry=10014;
UPDATE trinity_string SET content_loc4='The Horde has taken the East Beacon!' WHERE entry=10015;
UPDATE trinity_string SET content_loc4='The Alliance has taken the East Beacon!' WHERE entry=10016;
UPDATE trinity_string SET content_loc4='The Horde has captured the Twin Spire Graveyard!' WHERE entry=10017;
UPDATE trinity_string SET content_loc4='The Alliance has captured the Twin Spire Graveyard!' WHERE entry=10018;
UPDATE trinity_string SET content_loc4='The Horde lost the West Beacon!' WHERE entry=10019;
UPDATE trinity_string SET content_loc4='The Alliance lost the West Beacon!' WHERE entry=10020;
UPDATE trinity_string SET content_loc4='The Horde lost the East Beacon!' WHERE entry=10021;
UPDATE trinity_string SET content_loc4='The Alliance lost the East Beacon!' WHERE entry=10022;
UPDATE trinity_string SET content_loc4='The Horde lost the Twin Spire Graveyard!' WHERE entry=10023;
UPDATE trinity_string SET content_loc4='The Alliance lost the Twin Spire Graveyard!' WHERE entry=10024;
UPDATE trinity_string SET content_loc4='The Horde has captured Halaa!' WHERE entry=10025;
UPDATE trinity_string SET content_loc4='The Alliance has captured Halaa!' WHERE entry=10026;
UPDATE trinity_string SET content_loc4='The Horde lost Halaa!' WHERE entry=10027;
UPDATE trinity_string SET content_loc4='The Alliance lost Halaa!' WHERE entry=10028;
UPDATE trinity_string SET content_loc4='The Horde has taken a Spirit Tower!' WHERE entry=10029;
UPDATE trinity_string SET content_loc4='The Alliance has taken a Spirit Tower!' WHERE entry=10030;
UPDATE trinity_string SET content_loc4='The Horde lost a Spirit Tower!' WHERE entry=10031;
UPDATE trinity_string SET content_loc4='The Alliance lost a Spirit Tower!' WHERE entry=10032;
UPDATE trinity_string SET content_loc4='The Horde has taken the Northpass Tower!' WHERE entry=10033;
UPDATE trinity_string SET content_loc4='The Alliance has taken the Northpass Tower!' WHERE entry=10034;
UPDATE trinity_string SET content_loc4='The Horde has taken the Eastwall Tower!' WHERE entry=10035;
UPDATE trinity_string SET content_loc4='The Alliance has taken the Eastwall Tower!' WHERE entry=10036;
UPDATE trinity_string SET content_loc4='The Horde has taken the Crown Guard Tower!' WHERE entry=10037;
UPDATE trinity_string SET content_loc4='The Alliance has taken the Crown Guard Tower!' WHERE entry=10038;
UPDATE trinity_string SET content_loc4='The Horde has taken the Plaguewood Tower!' WHERE entry=10039;
UPDATE trinity_string SET content_loc4='The Alliance has taken the Plaguewood Tower!' WHERE entry=10040;
UPDATE trinity_string SET content_loc4='The Horde lost the Northpass Tower!' WHERE entry=10041;
UPDATE trinity_string SET content_loc4='The Alliance lost the Northpass Tower!' WHERE entry=10042;
UPDATE trinity_string SET content_loc4='The Horde lost the Eastwall Tower!' WHERE entry=10043;
UPDATE trinity_string SET content_loc4='The Alliance lost the Eastwall Tower!' WHERE entry=10044;
UPDATE trinity_string SET content_loc4='The Horde lost the Crown Guard Tower!' WHERE entry=10045;
UPDATE trinity_string SET content_loc4='The Alliance lost the Crown Guard Tower!' WHERE entry=10046;
UPDATE trinity_string SET content_loc4='The Horde lost the Plaguewood Tower!' WHERE entry=10047;
UPDATE trinity_string SET content_loc4='The Alliance lost the Plaguewood Tower!' WHERE entry=10048;
UPDATE trinity_string SET content_loc4='The Horde has collected 200 silithyst!' WHERE entry=10049;
UPDATE trinity_string SET content_loc4='The Alliance has collected 200 silithyst!' WHERE entry=10050;
UPDATE trinity_string SET content_loc4='Take me to Northpass Tower.' WHERE entry=10051;
UPDATE trinity_string SET content_loc4='Take me to Eastwall Tower.' WHERE entry=10052;
UPDATE trinity_string SET content_loc4='Take me to Crown Guard Tower.' WHERE entry=10053;
UPDATE trinity_string SET content_loc4='Give me the flag, I''ll take it to the central beacon for the glory of the Alliance!' WHERE entry=10054;
UPDATE trinity_string SET content_loc4='Give me the flag, I''ll take it to the central beacon for the glory of the Horde!' WHERE entry=10055;
UPDATE trinity_string SET content_loc4='|cffffff00[|cffff0000游戏公告|cffffff00]: %s|r' WHERE entry=11000;
UPDATE trinity_string SET content_loc4='You have not chosen -1 or the current realmID that you are on.' WHERE entry=11001;
UPDATE trinity_string SET content_loc4='Phasemask: %u' WHERE entry=5020;
UPDATE trinity_string SET content_loc4='Armor: %u' WHERE entry=5021;
UPDATE trinity_string SET content_loc4='泰坦大门已经被联盟占领!' WHERE entry=10063;
UPDATE trinity_string SET content_loc4='泰坦大门已经被部落占领!' WHERE entry=10064;
UPDATE trinity_string SET content_loc4='%s 已经被破坏了!' WHERE entry=10061;
UPDATE trinity_string SET content_loc4='第一回合-  完成!' WHERE entry=10062;
UPDATE trinity_string SET content_loc4='远古海滩战斗开启!勇士们.为了我们的荣耀，冲！' WHERE entry=10059;
UPDATE trinity_string SET content_loc4='%s 受到攻击!' WHERE entry=10060;
UPDATE trinity_string SET content_loc4='远古海滩战场将在30秒内开启!请各位玩家准备好.' WHERE entry=10058;
UPDATE trinity_string SET content_loc4='远古海滩战场将在2分钟内开启!' WHERE entry=10056;
UPDATE trinity_string SET content_loc4='远古海滩战场将在1分钟内开启!' WHERE entry=10057;
UPDATE trinity_string SET content_loc4='Channel password not changed due to channel being marked public. GM Powers required.' WHERE entry=5022;
UPDATE trinity_string SET content_loc4='这个是关闭着的.' WHERE entry=5008;
UPDATE trinity_string SET content_loc4='编码: %u' WHERE entry=5024;
UPDATE trinity_string SET content_loc4='类型: %u' WHERE entry=5025;
UPDATE trinity_string SET content_loc4='外观编码: %u' WHERE entry=5026;
UPDATE trinity_string SET content_loc4='名称: %s' WHERE entry=5027;
UPDATE trinity_string SET content_loc4='等级不足，需要升级到%d级。' WHERE entry=6604;
UPDATE trinity_string SET content_loc4='等级不足，需要升级到%d级，才能说。' WHERE entry=6605;
UPDATE trinity_string SET content_loc4='You cannot write to channels until you become level %d.' WHERE entry=6606;
UPDATE trinity_string SET content_loc4='You cannot use auction until you become level %d.' WHERE entry=6607;
UPDATE trinity_string SET content_loc4='You cannot write tickets until you become level %d.' WHERE entry=6608;
UPDATE trinity_string SET content_loc4='You cannot trade until you become level %d.' WHERE entry=6609;
UPDATE trinity_string SET content_loc4='You cannot trade with characters lower than level %d.' WHERE entry=6610;
UPDATE trinity_string SET content_loc4='You cannot send mail until you become level %d.' WHERE entry=6611;
UPDATE trinity_string SET content_loc4='You cannot send mail to characters lower than level %d.' WHERE entry=6612;
UPDATE trinity_string SET content_loc4='
|cff00ccff%s|r |cff00ff00Added comment|r: "%s"|r ' WHERE entry=2024;
UPDATE trinity_string SET content_loc4='|%15s| %20s | %15s |%4d| %9d |' WHERE entry=1013;
UPDATE trinity_string SET content_loc4='-======================== Characters Online =======================-' WHERE entry=1015;
UPDATE trinity_string SET content_loc4='This Battleground have been disabled. You can''t join the queue.' WHERE entry=747;
UPDATE trinity_string SET content_loc4='Arenas have been disabled. You can''t join the queue.' WHERE entry=748;
UPDATE trinity_string SET content_loc4='物品 ''%i'' 已经在商人的列表里存在了.' WHERE entry=210;
UPDATE trinity_string SET content_loc4='Entry %u not found in creature_template table.' WHERE entry=817;
UPDATE trinity_string SET content_loc4='Entry %u not found in sCreatureStorage. Possible new line in creature_template, but you can not add new creatures without restarting. Only modifing is allowed.' WHERE entry=818;
UPDATE trinity_string SET content_loc4='Round 2 of the Battle for the Strand of the Ancients begins in 1 minute.' WHERE entry=10065;
UPDATE trinity_string SET content_loc4='Round 2 begins in 30 seconds. Prepare yourselves!' WHERE entry=10066;
UPDATE trinity_string SET content_loc4='The chamber has been breached! The titan relic is vulnerable!' WHERE entry=10067;
UPDATE trinity_string SET content_loc4='The Alliance captured the South Graveyard!' WHERE entry=10068;
UPDATE trinity_string SET content_loc4='The Alliance captured the West Graveyard!' WHERE entry=10069;
UPDATE trinity_string SET content_loc4='The Alliance captured the East Graveyard!' WHERE entry=10070;
UPDATE trinity_string SET content_loc4='The Horde captured the South Graveyard!' WHERE entry=10071;
UPDATE trinity_string SET content_loc4='The Horde captured the West Graveyard!' WHERE entry=10072;
UPDATE trinity_string SET content_loc4='The Horde captured the East Graveyard!' WHERE entry=10073;
UPDATE trinity_string SET content_loc4='One on more parameters have incorrect values' WHERE entry=62;
UPDATE trinity_string SET content_loc4='| GUID       | Name                 | Account                      | Delete Date         |' WHERE entry=1016;
UPDATE trinity_string SET content_loc4='| %10u | %20s | %15s (%10u) | %19s |' WHERE entry=1017;
UPDATE trinity_string SET content_loc4='没有人物被找到.' WHERE entry=1019;
UPDATE trinity_string SET content_loc4='Restoring the following characters:' WHERE entry=1020;
UPDATE trinity_string SET content_loc4='Deleting the following characters:' WHERE entry=1021;
UPDATE trinity_string SET content_loc4='ERROR: You can only assign a new name if you have only selected a single character!' WHERE entry=1022;
UPDATE trinity_string SET content_loc4='Character ''%s'' (GUID: %u Account %u) can''t be restored: account not exist!' WHERE entry=1023;
UPDATE trinity_string SET content_loc4='Character ''%s'' (GUID: %u Account %u) can''t be restored: account character list full!' WHERE entry=1024;
UPDATE trinity_string SET content_loc4='Character ''%s'' (GUID: %u Account %u) can''t be restored: new name already used!' WHERE entry=1025;
UPDATE trinity_string SET content_loc4='GUID: %u Name: %s Account: %s (%u) Date: %s' WHERE entry=1026;
UPDATE trinity_string SET content_loc4='Lootid: %u' WHERE entry=5028;
UPDATE trinity_string SET content_loc4='Can''t dump deleted characters,aborting.' WHERE entry=1130;
UPDATE trinity_string SET content_loc4='Result limit reached (max results: %d)' WHERE entry=5029;
UPDATE trinity_string SET content_loc4='The following characters match your query:' WHERE entry=1131;
UPDATE trinity_string SET content_loc4='Currently Banned Characters:' WHERE entry=1132;
UPDATE trinity_string SET content_loc4='|   Character   |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |' WHERE entry=1133;
UPDATE trinity_string SET content_loc4='Areatrigger debugging turned on.' WHERE entry=1202;
UPDATE trinity_string SET content_loc4='Areatrigger debugging turned off.' WHERE entry=1203;
UPDATE trinity_string SET content_loc4='You have reached areatrigger %u.' WHERE entry=1204;
UPDATE trinity_string SET content_loc4='城市' WHERE entry=819;
UPDATE trinity_string SET content_loc4='无效的目标' WHERE entry=63;
UPDATE trinity_string SET content_loc4='你必须达到58级，才能使用这个功能.' WHERE entry=65;
UPDATE trinity_string SET content_loc4='Sending tickets is allowed.' WHERE entry=1134;
UPDATE trinity_string SET content_loc4='Sending tickets is not allowed.' WHERE entry=1135;
UPDATE trinity_string SET content_loc4='SQL driver query logging enabled.' WHERE entry=1027;
UPDATE trinity_string SET content_loc4='SQL driver query logging disabled.' WHERE entry=1028;
UPDATE trinity_string SET content_loc4='Channel: %s publicity set to: %u' WHERE entry=5023;
UPDATE trinity_string SET content_loc4='You cannot use that item here.' WHERE entry=64;
UPDATE trinity_string SET content_loc4='本次战斗将在2分钟内开始.' WHERE entry=1205;
UPDATE trinity_string SET content_loc4='本次战斗将在1分钟内开始.' WHERE entry=1206;
UPDATE trinity_string SET content_loc4='战斗开始了！' WHERE entry=1208;
UPDATE trinity_string SET content_loc4='本次战斗将在30秒内开始!' WHERE entry=1207;
UPDATE trinity_string SET content_loc4='已被联盟占领' WHERE entry=1209;
UPDATE trinity_string SET content_loc4='已被部落占领' WHERE entry=1210;
UPDATE trinity_string SET content_loc4='%s 赢得了胜利!' WHERE entry=1211;
UPDATE trinity_string SET content_loc4='西大门 %s 被破坏!' WHERE entry=1212;
UPDATE trinity_string SET content_loc4='The east gate of %s is destroyed!' WHERE entry=1213;
UPDATE trinity_string SET content_loc4='The south gate of %s is destroyed!' WHERE entry=1214;
UPDATE trinity_string SET content_loc4='The north gate of %s is destroyed!' WHERE entry=1215;
UPDATE trinity_string SET content_loc4='$n has assaulted the %s' WHERE entry=1216;
UPDATE trinity_string SET content_loc4='$n has defended the %s' WHERE entry=1217;
UPDATE trinity_string SET content_loc4='$n claims the %s! If left unchallenged, the %s will control it in 1 minute!' WHERE entry=1218;
UPDATE trinity_string SET content_loc4='The %s has taken the %s' WHERE entry=1219;
UPDATE trinity_string SET content_loc4='车间' WHERE entry=1220;
UPDATE trinity_string SET content_loc4='码头' WHERE entry=1221;
UPDATE trinity_string SET content_loc4='精炼厂' WHERE entry=1222;
UPDATE trinity_string SET content_loc4='矿厂' WHERE entry=1223;
UPDATE trinity_string SET content_loc4='机场' WHERE entry=1224;
UPDATE trinity_string SET content_loc4='Requires Maiden of Winter''s Breath Lake' WHERE entry=1334;
UPDATE trinity_string SET content_loc4='You can''t use that right now' WHERE entry=1335;
UPDATE trinity_string SET content_loc4='You have disabled %s''s chat for %u minutes, effective at the player''s next login. Reason: %s.' WHERE entry=283;
UPDATE trinity_string SET content_loc4='命令提示：命令 .pinfo 不支持  ''rep'' 选择,玩家不在线.' WHERE entry=550;
UPDATE trinity_string SET content_loc4='Map: %s, Area: %s' WHERE entry=716;
UPDATE trinity_string SET content_loc4='Map: %s, Area: %s, Zone: %s, Phase: %u' WHERE entry=714;
UPDATE trinity_string SET content_loc4='Character %s has never been banned!' WHERE entry=1136;
UPDATE trinity_string SET content_loc4='%s attempts to run away in fear!' WHERE entry=5030;
UPDATE trinity_string SET content_loc4='Dev mode is ON' WHERE entry=1137;
UPDATE trinity_string SET content_loc4='All closed tickets were deleted and counter is reseted to |cffff00ff 1|r' WHERE entry=2028;
UPDATE trinity_string SET content_loc4='Battle begins!' WHERE entry=756;
UPDATE trinity_string SET content_loc4='%s has successfully defended the fortress!' WHERE entry=757;
UPDATE trinity_string SET content_loc4='%s has taken over the fortress!' WHERE entry=758;
UPDATE trinity_string SET content_loc4='The %s siege workshop has been damaged by the %s!' WHERE entry=759;
UPDATE trinity_string SET content_loc4='The %s siege workshop has been destroyed by the %s!' WHERE entry=760;
UPDATE trinity_string SET content_loc4='The %s tower has been damaged!' WHERE entry=761;
UPDATE trinity_string SET content_loc4='The %s tower has been destroyed!' WHERE entry=762;
UPDATE trinity_string SET content_loc4='Wintergrasp fortress is under attack!' WHERE entry=763;
UPDATE trinity_string SET content_loc4='Wintergrasp is now under the control of the %s.' WHERE entry=764;
UPDATE trinity_string SET content_loc4='Wintergrasp timer set to %s.' WHERE entry=765;
UPDATE trinity_string SET content_loc4='Wintergrasp battle started.' WHERE entry=766;
UPDATE trinity_string SET content_loc4='Wintergrasp battle finished.' WHERE entry=767;
UPDATE trinity_string SET content_loc4='Wintergrasp info: %s controlled. Timer: %s. Wartime: %s. Number of Players: (Horde: %u, Alliance: %u)' WHERE entry=768;
UPDATE trinity_string SET content_loc4='Wintergrasp outdoorPvP is disabled.' WHERE entry=769;
UPDATE trinity_string SET content_loc4='Wintergrasp outdoorPvP is enabled.' WHERE entry=770;
UPDATE trinity_string SET content_loc4='You have reached Rank 1: Corporal' WHERE entry=771;
UPDATE trinity_string SET content_loc4='You have reached Rank 2: First Lieutenant' WHERE entry=772;
UPDATE trinity_string SET content_loc4='Before the Battle of  Wintergrasp left 30 minutes!' WHERE entry=780;
UPDATE trinity_string SET content_loc4='Before the Battle of  Wintergrasp left 10 minutes! Portal from Dalaran will work at begin of the battle.' WHERE entry=781;
UPDATE trinity_string SET content_loc4='The battle for Wintergrasp  has stopped! Not enough defenders. Wintergrasp Fortress remains  Attackers.' WHERE entry=782;
UPDATE trinity_string SET content_loc4='The battle for Wintergrasp  has stopped! Not enough attackers. Wintergrasp Fortress remains  Defenders.' WHERE entry=783;
UPDATE trinity_string SET content_loc4='|cFFFFFC00[ANTICHEAT]|cFF00FFFF[|cFF60FF00%s|cFF00FFFF] Banned for cheating!|r' WHERE entry=11002;
UPDATE trinity_string SET content_loc4='There are pending open tickets, please close them first!' WHERE entry=2027;
UPDATE trinity_string SET content_loc4='Dev mode is OFF' WHERE entry=1138;
UPDATE trinity_string SET content_loc4='You are jailed by ''%s'' for %u hour(s)!' WHERE entry=950;
UPDATE trinity_string SET content_loc4='%s'' wrote this as reason: ''%s''' WHERE entry=951;
UPDATE trinity_string SET content_loc4='%s'' was jailed by you for %u hour(s).' WHERE entry=952;
UPDATE trinity_string SET content_loc4='You was released out of the jail by %s.' WHERE entry=953;
UPDATE trinity_string SET content_loc4='You have released %s out of the jail.' WHERE entry=954;
UPDATE trinity_string SET content_loc4='No reason given or reason is < %u chars!' WHERE entry=955;
UPDATE trinity_string SET content_loc4='No name given!' WHERE entry=956;
UPDATE trinity_string SET content_loc4='No time given!' WHERE entry=957;
UPDATE trinity_string SET content_loc4='The jailtime must be between 1 and %u hours!' WHERE entry=958;
UPDATE trinity_string SET content_loc4='The character ''%s'' is not jailed!' WHERE entry=959;
UPDATE trinity_string SET content_loc4='Command forbidden for jailed characters!' WHERE entry=960;
UPDATE trinity_string SET content_loc4='You have %u hour(s) left in the jail.' WHERE entry=961;
UPDATE trinity_string SET content_loc4='You have %u minute(s) left in the jail.' WHERE entry=962;
UPDATE trinity_string SET content_loc4='You''re a free like a bird! ;
-)' WHERE entry=963;
UPDATE trinity_string SET content_loc4='%s was %u times jailed and has %u minute(s) left. Last time jailed by %s. Last reason was: ''%s''' WHERE entry=964;
UPDATE trinity_string SET content_loc4='%s'' was never jailed.' WHERE entry=965;
UPDATE trinity_string SET content_loc4='You can''t jail yourself!' WHERE entry=966;
UPDATE trinity_string SET content_loc4='You can''t unjail yourself!' WHERE entry=967;
UPDATE trinity_string SET content_loc4='|cffff0000[!!! ATTENTION - IMPORTANT - WARNING !!!
 You were already %u times in prison. If you are in Jail for a total of  %u times, your character will be deleted
|cffff0000!!! ATTENTION - IMPORTANT - WARNING !!!]' WHERE entry=968;
UPDATE trinity_string SET content_loc4='The character ''' WHERE entry=969;
UPDATE trinity_string SET content_loc4=' was jailed for ' WHERE entry=970;
UPDATE trinity_string SET content_loc4=' hour(s) by the GM character ''' WHERE entry=971;
UPDATE trinity_string SET content_loc4='. The reason is: ' WHERE entry=972;
UPDATE trinity_string SET content_loc4='The jail configuration was reloaded.' WHERE entry=973;
UPDATE trinity_string SET content_loc4='>> Trinity Jail config loaded.' WHERE entry=974;
UPDATE trinity_string SET content_loc4='Can''t load jail config! Table empty or missed! Use characters_jail.sql!' WHERE entry=975;
UPDATE trinity_string SET content_loc4='Set all jail config settings to default...' WHERE entry=976;
UPDATE trinity_string SET content_loc4='The Character ''%s''  is jailed and teleportet into the jail.' WHERE entry=977;
UPDATE trinity_string SET content_loc4='The Character ''%s''  was released out of the jail.' WHERE entry=978;
UPDATE trinity_string SET content_loc4='A character with this name doesn''t exists!' WHERE entry=979;
UPDATE trinity_string SET content_loc4='|cffff0000[!!! ATTENTION - IMPORTANT - WARNING !!!
 You were already %u times in prison. If you are in Jail for a total of  %u times, your account  will be banned!
|cffff0000!!! ATTENTION - IMPORTANT - WARNING !!!]' WHERE entry=980;
UPDATE trinity_string SET content_loc4='Max. jailtimes reached!' WHERE entry=981;
UPDATE trinity_string SET content_loc4='Robotron' WHERE entry=982;
UPDATE trinity_string SET content_loc4='Your Jail status was reset to 0 ' WHERE entry=983;
UPDATE trinity_string SET content_loc4='AI名称: %s 脚本名称: %s' WHERE entry=5031;

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15070,"[PvP] 你越级杀死了玩家（%s）, 获得了额外%d荣耀点奖励!","你越级杀死了玩家（%s）, 获得了额外%d荣耀点奖励!");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15071,"[PvP] 你被等级比你低的玩家（%s）杀死了, 额外损失了%d荣耀点!","你被等级比你低的玩家（%s）杀死了, 额外损失了%d荣耀点!");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15072,"[PvP] 你被其他玩家（%s）杀死了, 额外损失了%d铜币!","你被其他玩家（%s）杀死了, 额外损失了%d铜币!");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15073,"[PvP] 你杀死了玩家（%s）, 获得了%d铜币奖励!","你杀死了玩家（%s）, 获得了%d铜币奖励!");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15074,"[PvP] 你可耻的杀死了比你等级低很多的玩家（%s）, 扣除%d荣耀点作为惩罚!","你可耻的杀死了比你等级低很多的玩家（%s）, 扣除%d荣耀点作为惩罚！");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15075,"You have been awarded a token for slaying another player!","你杀死了其他玩家，得到了一个勋章奖励！");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15076,"You don't have any space in your bags.","你背包没有空间了。");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15077,"You were killed by others and lost the item [%s]x%d","你被杀死后，丢失了[%s]x%d");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15078,"Dalaran","传到达拉然");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15079,"Query Membership Score","货币积分查询");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15080,"Summon Trainer","召唤训练师");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15081,"Membership Shop","杂货商人（未开放）");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15082,"Rider Shop","坐骑商人（未开放）");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15083,"Query Membership Level","会员服务（未开放）");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15084,"Summon trainer successfully","您临时召唤了一个训练师，有效时间5分钟");

REPLACE  into world.trinity_string (entry,content_default,content_loc4) 
values (15085,"Summon trainer failed!","召唤训练师失败");

SET @STRING_ENTRY := 11100;
REPLACE INTO `trinity_string` (`entry`, `content_default`,`content_loc4`,`content_loc5`) VALUES
(@STRING_ENTRY+0, 'Item transmogrified','装备已被幻化','装备已被幻化'),
(@STRING_ENTRY+1, 'Equipment slot is empty','装备槽是空的','装备槽是空的'),
(@STRING_ENTRY+2, 'Invalid source item selected','选择的要被幻化的装备无效','选择的要被幻化的装备无效'),
(@STRING_ENTRY+3, 'Source item does not exist','要被幻化的装备不存在','要被幻化的装备不存在'),
(@STRING_ENTRY+4, 'Destination item does not exist','幻化材料装备不存在','幻化材料装备不存在'),
(@STRING_ENTRY+5, 'Selected items are invalid','选择的装备无效','选择的装备无效'),
(@STRING_ENTRY+6, 'Not enough money','兜里没钱啊','兜里没钱啊'),
(@STRING_ENTRY+7, 'You don\'t have enough tokens','没有足够的令牌','没有足够的令牌'),
(@STRING_ENTRY+8, 'Transmogrifications removed','幻化已经被复原','幻化已经被复原'),
(@STRING_ENTRY+9, 'There are no transmogrifications','没有幻化过的装备','没有幻化过的装备'),
(@STRING_ENTRY+10, 'Invalid name inserted','插入名字无效','插入名字无效');


REPLACE INTO `trinity_string` (`entry`, `content_default`,`content_loc4`,`content_loc5`) VALUES
(15100, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tHow transmogrification works','|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|t幻化介绍','|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|t幻化介绍'),
(15101, 'Head','头盔','头盔'),
(15102, 'Shoulders','护肩','护肩'),
(15103, 'Shirt','衣服','衣服'),
(15104, 'Chest','胸甲','胸甲'),
(15105, 'Waist','护腰','护腰'),
(15106, 'Legs','护腿','护腿'),
(15107, 'Feet','鞋子','鞋子'),
(15108, 'Wrists','护腕','护腕'),
(15109, 'Hands','手套','手套'),
(15110, 'Back','返回..','返回..'),
(15111, 'Main hand','主武器','主武器'),
(15112, 'Off hand','副武器','副武器'),
(15113, 'Ranged','远程','远程'),
(15114, 'Tabard','斗篷','斗篷'),
(15115, '|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|tManage sets','|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|t幻化套装管理','|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|t幻化套装管理'),
(15116, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tRemove all transmogrifications','|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|t移除所有幻化','|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|t移除所有幻化'),
(15117, '|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|tUpdate menu','|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|t更新菜单','|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|t更新菜单'),
(15118, 'Remove transmogrifications from all equipped items?','请确认是否要去除所有装备的幻化效果？','请确认是否要去除所有装备的幻化效果？'),
(15119, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tHow sets work','|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|t套装介绍','|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|t套装介绍'),
(15120, '|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|tSave set','|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|tS保存套装','|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|tS保存套装'),
(15121, '|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|tUse set','|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|t使用套装','|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|t使用套装'),
(15122, '|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|tDelete set','|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|t删除套装','|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|t删除套装'),
(15123, 'Using this set for transmogrify will bind transmogrified items to you and make them non-refundable and non-tradeable.\nDo you wish to continue?\n\n','使用这套幻化套装将使你相关装备与你绑定，并且这些装备无法被交易或退还。\n是否继续？\n\n','使用这套幻化套装将使你相关装备与你绑定，并且这些装备无法被交易或退还。\n是否继续？\n\n'),
(15124, 'Are you sure you want to delete ','请确认是否删除','请确认是否删除'),
(15125, 'Insert set name ','请输入套装名称','请输入套装名称'),
(15126, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tRemove transmogrification','|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|t移除幻化','|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|t移除幻化'),
(15127, 'Remove transmogrification from the slot?','是否从装备槽中移除幻化效果？','是否从装备槽中移除幻化效果？');
